-- Admin RBAC migration for Kingdom Fellowship Christian Church
-- Run this in the Supabase SQL Editor after the updated supabase-schema.sql.
-- This migration is safe for the existing administrator: it does not change passwords.

begin;

-- Ensure older installations receive the new columns.
alter table public.admin_users add column if not exists is_active boolean not null default true;
alter table public.admin_users add column if not exists created_at timestamptz not null default now();
alter table public.admin_users add column if not exists updated_at timestamptz not null default now();
alter table public.admin_users add column if not exists last_login_at timestamptz;

-- Normalize the current administrator to the new top-level role.
update public.admin_users
set role = 'super_admin', is_active = true, updated_at = now()
where role = 'admin';

-- Permission catalogue. These are application permission names; users can later
-- receive only the permissions appropriate to their responsibilities.
create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.admin_users(id) on delete cascade,
  permission text not null,
  created_at timestamptz not null default now(),
  unique(user_id, permission)
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.admin_users(id) on delete set null,
  action text not null,
  resource text,
  resource_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_permissions_user_id_idx on public.admin_permissions(user_id);
create index if not exists admin_audit_log_user_id_idx on public.admin_audit_log(user_id);
create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log(created_at desc);

alter table public.admin_users enable row level security;
alter table public.admin_permissions enable row level security;
alter table public.admin_audit_log enable row level security;

commit;

-- Planned permission names for the application layer:
-- site.view
-- site.edit
-- media.view
-- media.upload
-- media.edit
-- media.delete
-- comments.view
-- comments.moderate
-- live.view
-- live.edit
-- theme.view
-- theme.edit
-- users.view
-- users.create
-- users.edit
-- users.disable
-- users.delete
-- users.permissions
-- audit.view
