-- RBAC database foundation for Kingdom Fellowship Christian Church.
-- Run after supabase-schema.sql.
-- This migration does not change passwords.

begin;

alter table public.admin_users add column if not exists is_active boolean not null default true;
alter table public.admin_users add column if not exists created_at timestamptz not null default now();
alter table public.admin_users add column if not exists updated_at timestamptz not null default now();
alter table public.admin_users add column if not exists last_login_at timestamptz;

create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.admin_users(id) on delete cascade,
  permission text not null,
  created_at timestamptz not null default now(),
  unique(user_id, permission)
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.admin_users(id) on delete set null,
  action text not null,
  resource text,
  resource_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_permissions_user_id_idx on public.admin_permissions(user_id);
create index if not exists admin_audit_log_user_id_idx on public.admin_audit_log(user_id);
create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log(created_at desc);

-- Promote ONLY the existing administrator account.
-- Username comparison is case-insensitive. Password is untouched.
update public.admin_users
set role = 'super_admin',
    is_active = true,
    updated_at = now()
where lower(username) = lower('Deno');

alter table public.admin_users enable row level security;
alter table public.admin_permissions enable row level security;
alter table public.admin_audit_log enable row level security;

commit;
