-- Revision history for CMS pages.
-- Run after cms-migration.sql.

create table if not exists public.cms_page_revisions (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.cms_pages(id) on delete cascade,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists cms_page_revisions_page_idx on public.cms_page_revisions(page_id, created_at desc);
alter table public.cms_page_revisions enable row level security;
