-- Page and navigation management for the church CMS.
-- Run after supabase-schema.sql and admin-rbac-migration.sql.

create table if not exists public.cms_pages (
  id bigint generated by default as identity primary key,
  slug text unique not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  internal_name text not null,
  menu_label text not null,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  show_in_navigation boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.cms_sections (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.cms_pages(id) on delete cascade,
  section_type text not null check (section_type in ('hero','text','image_text','gallery','cards','events','services','video','youtube','live','contact','cta','giving','custom')),
  position integer not null default 0,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(page_id, position)
);
create table if not exists public.cms_navigation (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null,
  parent_id bigint references public.cms_navigation(id) on delete cascade,
  position integer not null default 0,
  is_visible boolean not null default true,
  page_id bigint references public.cms_pages(id) on delete set null,
  unique(parent_id, position)
);
create index if not exists cms_sections_page_idx on public.cms_sections(page_id, position);
create index if not exists cms_navigation_parent_idx on public.cms_navigation(parent_id, position);
alter table public.cms_pages enable row level security;
alter table public.cms_sections enable row level security;
alter table public.cms_navigation enable row level security;
