-- Structured Events content model for Kingdom Fellowship Christian Church
-- Keep recurring worship/service schedules in site_content.services.
-- Events are special programs with their own lifecycle and publishing controls.

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text not null default 'General',
  short_description text not null default '',
  description text not null default '',
  image text not null default '',
  flyer_url text not null default '',
  start_at timestamptz not null,
  end_at timestamptz,
  all_day boolean not null default false,
  location text not null default '',
  address text not null default '',
  attendance_type text not null default 'in_person',
  registration_url text not null default '',
  contact text not null default '',
  livestream_url text not null default '',
  featured boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists events_status_start_idx on public.events(status, start_at);
create index if not exists events_featured_idx on public.events(featured, status, start_at);
create index if not exists events_category_idx on public.events(category);

alter table public.events enable row level security;

drop policy if exists "Public published events read" on public.events;
create policy "Public published events read"
  on public.events
  for select
  to anon, authenticated
  using (status = 'published');

-- Keep updated_at current for direct Supabase updates.
create or replace function public.set_events_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists events_updated_at on public.events;
create trigger events_updated_at
before update on public.events
for each row execute function public.set_events_updated_at();
