-- Live chat v2: persistent threaded replies and shared reactions.
-- Run this migration in Supabase SQL Editor after live-comments-schema.sql.

alter table public.live_comments
  add column if not exists parent_id bigint references public.live_comments(id) on delete cascade;

create index if not exists live_comments_parent_id_idx
  on public.live_comments(parent_id);

create table if not exists public.live_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.live_comments(id) on delete cascade,
  reaction text not null check (reaction in ('heart','pray','clap')),
  visitor_id text not null check (char_length(visitor_id) between 16 and 128),
  created_at timestamptz not null default now(),
  unique(comment_id, reaction, visitor_id)
);

create index if not exists live_comment_reactions_comment_idx
  on public.live_comment_reactions(comment_id);

alter table public.live_comment_reactions enable row level security;

drop policy if exists "Public live reaction read" on public.live_comment_reactions;
create policy "Public live reaction read"
on public.live_comment_reactions for select to anon, authenticated
using (true);

-- Public clients must write through the server/service-role API.
-- This prevents anonymous users from bypassing server validation.

drop policy if exists "Public live reaction insert" on public.live_comment_reactions;

-- Helpful view for retrieving reaction totals alongside comments.
create or replace view public.live_comment_reaction_counts as
select
  comment_id,
  count(*) filter (where reaction = 'heart') as heart_count,
  count(*) filter (where reaction = 'pray') as pray_count,
  count(*) filter (where reaction = 'clap') as clap_count
from public.live_comment_reactions
group by comment_id;

-- Preserve the existing approved-comment public-read policy.
-- Replies inherit moderation through their own approved flag.
