-- Persistent comments for the dedicated Live page.
create table if not exists public.live_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  comment text not null check (char_length(comment) between 1 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.live_comments enable row level security;

-- The server uses the Supabase service-role key, so these policies do not expose
-- write access to the public browser. They also document the intended public-read model.
drop policy if exists "Public approved live comments read" on public.live_comments;
create policy "Public approved live comments read"
on public.live_comments for select to anon, authenticated
using (approved = true);
