-- Persistent comments for the public Live page.
create table if not exists public.live_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  comment text not null check (char_length(comment) between 1 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.live_comments enable row level security;

drop policy if exists "Public live comments read" on public.live_comments;
create policy "Public live comments read"
on public.live_comments for select to anon, authenticated
using (approved = true);

drop policy if exists "Public live comments insert" on public.live_comments;
create policy "Public live comments insert"
on public.live_comments for insert to anon, authenticated
with check (approved = true and char_length(name) between 1 and 60 and char_length(comment) between 1 and 500);

-- The server uses the Supabase service-role key for moderation and therefore bypasses RLS.
