await ensureAdminUser();
await ensureDefaultSiteContent();

const app=express(); const port=process.env.PORT||3001; if(isProduction)app.set('trust proxy',1); app.disable('x-powered-by');
app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(isProduction)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next();});
app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:true,limit:'1mb'})); app.use(session({secret:process.env.SESSION_SECRET||'development-only-session-secret',resave:false,saveUninitialized:false,cookie:{maxAge:1000*60*60*12,httpOnly:true,sameSite:'lax',secure:isProduction}}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024},fileFilter:(_req,file,cb)=>new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime','audio/mpeg','audio/mp4','audio/wav','audio/ogg','audio/webm','application/pdf']).has(file.mimetype)?cb(null,true):cb(new Error('Unsupported file type. Upload an image, video, audio file, or PDF.'))});
function requireAdmin(req,res,next){if(!req.session.user)return res.status(401).json({error:'Unauthorized. Please log in.'});next();} function requireSameOrigin(req,res,next){const origin=req.get('Origin');const host=req.get('Host');if(!origin)return next();try{const originUrl=new URL(origin);if(originUrl.host!==host||!['http:','https:'].includes(originUrl.protocol))return res.status(403).json({error:'Cross-site request blocked.'});}catch(_error){return res.status(403).json({error:'Invalid request origin.'});}next();}
const loginAttempts=new Map(),LOGIN_WINDOW_MS=15*60*1000,LOGIN_MAX_ATTEMPTS=10;function loginKey(req){return`${req.ip}:${String(req.body?.username||'').trim().toLowerCase()}`;}function isRateLimited(key){const entry=loginAttempts.get(key);if(!entry||Date.now()-entry.startedAt>LOGIN_WINDOW_MS){loginAttempts.delete(key);return false;}return entry.count>=LOGIN_MAX_ATTEMPTS;}function recordFailedLogin(key){const now=Date.now(),entry=loginAttempts.get(key);if(!entry||now-entry.startedAt>LOGIN_WINDOW_MS)loginAttempts.set(key,{startedAt:now,count:1});else entry.count+=1;}function clearLoginAttempts(key){loginAttempts.delete(key);}
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'aic-kitanga-admin',database:useSupabase?'supabase':'sqlite'}));
app.post('/api/admin/login',requireSameOrigin,async(req,res)=>{try{const{username,password}=req.body||{},key=loginKey(req);if(isRateLimited(key))return res.status(429).json({error:'Too many login attempts. Please try again later.'});const user=await dbGetAdmin(username);if(!user||!bcrypt.compareSync(password||'',user.password_hash)){recordFailedLogin(key);return res.status(401).json({error:'Invalid username or password.'});}clearLoginAttempts(key);req.session.regenerate(error=>{if(error)return res.status(500).json({error:'Unable to create a secure session.'});req.session.user={id:user.id,username:user.username,role:user.role};res.json({ok:true,user:req.session.user});});}catch(error){console.error(error);res.status(500).json({error:'Unable to log in.'});}});
app.post('/api/admin/logout',requireSameOrigin,(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/admin/session',(req,res)=>{if(!req.session.user)return res.status(401).json({loggedIn:false});res.json({loggedIn:true,user:req.session.user});});
app.get('/api/site/content',async(_req,res)=>{try{res.json(await getSiteContent());}catch(error){console.error(error);res.status(500).json({error:'Unable to load site content.'});}});
app.put('/api/site/content',requireSameOrigin,requireAdmin,async(req,res)=>{try{await saveSiteContent(req.body||{});res.json({ok:true});}catch(error){console.error(error);res.status(500).json({error:'Unable to save site content.'});}});
app.get('/api/live/comments',async(_req,res)=>{try{res.json(await listLiveComments());}catch(error){console.error(error);res.status(500).json({error:'Unable to load live comments.'});}});
app.post('/api/live/comments',requireSameOrigin,async(req,res)=>{try{const item=await addLiveComment(req.body?.name,req.body?.comment);res.status(201).json(item);}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to post comment.'});}});
app.get('/api/admin/live/comments',requireAdmin,async(_req,res)=>{try{res.json(await listLiveComments({admin:true}));}catch(error){console.error(error);res.status(500).json({error:'Unable to load live comments.'});}});
app.patch('/api/admin/live/comments/:id',requireSameOrigin,requireAdmin,async(req,res)=>{try{const item=await moderateLiveComment(req.params.id,req.body?.approved);res.json(item);}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to update comment.'});}});
app.delete('/api/admin/live/comments/:id',requireSameOrigin,requireAdmin,async(req,res)=>{try{await deleteLiveComment(req.params.id);res.json({ok:true});}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to delete comment.'});}});
app.get('/api/media',async(_req,res)=>{try{res.json(await listMedia());}catch(error){console.error(error);res.status(500).json({error:'Unable to load media.'});}});