import express from 'express';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import multer from 'multer';
import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createClient } from '@supabase/supabase-js';
import { DEFAULT_SITE_CONTENT, mergeSiteContent } from './site-config.js';
import { registerAdminRbacRoutes } from './admin-rbac-routes.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const isProduction = process.env.NODE_ENV === 'production';
const useSupabase = Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
const dbDir = process.env.DATA_DIR || path.join(__dirname, 'data');
const uploadDir = process.env.UPLOAD_DIR || path.join(__dirname, 'uploads');

if (isProduction) {
  const required = ['ADMIN_USERNAME', 'ADMIN_PASSWORD', 'SESSION_SECRET'];
  const missing = required.filter(name => !process.env[name]);
  if (missing.length) throw new Error(`Missing required production environment variables: ${missing.join(', ')}`);
  if (process.env.SESSION_SECRET.length < 32) throw new Error('SESSION_SECRET must be at least 32 characters in production.');
  if (!useSupabase) console.warn('Supabase environment variables are not configured; temporarily using SQLite. Configure Supabase before the next production redeploy to make data persistent.');
}

if (!useSupabase) {
  fs.mkdirSync(dbDir, { recursive: true });
  fs.mkdirSync(uploadDir, { recursive: true });
}

const supabase = useSupabase
  ? createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } })
  : null;
const STORAGE_BUCKET = process.env.SUPABASE_STORAGE_BUCKET || 'church-media';

const sqlite = fs.existsSync(path.join(dbDir, 'site.db'))
  ? new Database(path.join(dbDir, 'site.db'))
  : (!useSupabase ? new Database(path.join(dbDir, 'site.db')) : null);
if (sqlite) sqlite.pragma('journal_mode = WAL');

async function ensureSupabaseStorage() {
  if (!supabase) return;
  const { data, error } = await supabase.storage.getBucket(STORAGE_BUCKET);
  if (!error && data) return;
  const created = await supabase.storage.createBucket(STORAGE_BUCKET, { public: true, fileSizeLimit: '50MB' });
  if (created.error && !/already exists/i.test(created.error.message || '')) throw new Error(`Unable to create Supabase storage bucket: ${created.error.message}`);
}
async function ensureSupabaseDatabase() {
  if (!supabase) return;
  const { error } = await supabase.from('site_content').select('key').limit(1);
  if (error) throw new Error(`Supabase schema is not ready. Run supabase-schema.sql in the Supabase SQL Editor. ${error.message}`);
}
function parseStoredValue(value) { if (typeof value !== 'string') return value; const trimmed = value.trim(); if (!trimmed) return ''; try { if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) return JSON.parse(trimmed); } catch (_) {} return value; }
async function ensureDefaultSiteContent() {
  if (useSupabase) { const rows = Object.entries(DEFAULT_SITE_CONTENT).map(([key, value]) => ({ key, value: typeof value === 'string' ? value : JSON.stringify(value) })); const { error } = await supabase.from('site_content').upsert(rows, { onConflict: 'key', ignoreDuplicates: true }); if (error) throw error; return; }
  const insert = sqlite.prepare('INSERT OR IGNORE INTO site_content (key, value) VALUES (?, ?)'); Object.entries(DEFAULT_SITE_CONTENT).forEach(([key, value]) => insert.run(key, typeof value === 'string' ? value : JSON.stringify(value)));
}
async function initDatabase() {
  if (useSupabase) { await ensureSupabaseDatabase(); await ensureSupabaseStorage(); return; }
  sqlite.exec(`CREATE TABLE IF NOT EXISTS admin_users (id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'admin');CREATE TABLE IF NOT EXISTS site_content (key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS media_items (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,type TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'general',description TEXT DEFAULT '',url TEXT NOT NULL,file_path TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
}
async function ensureAdminUser() {
  const username = process.env.ADMIN_USERNAME || (isProduction ? null : 'admin'); const password = process.env.ADMIN_PASSWORD || (isProduction ? null : 'admin123'); if (!username || !password) throw new Error('Admin credentials are required.');
  if (useSupabase) {
    const { data: row, error } = await supabase.from('admin_users').select('*').eq('username', username).maybeSingle();
    if (error) throw error;
    const hash = bcrypt.hashSync(password, 10);
    if (!row) {
      const result = await supabase.from('admin_users').insert({ username, password_hash: hash, role: 'admin', is_active: true }).select().single();
      if (result.error) throw result.error;
    } else if (!bcrypt.compareSync(password, row.password_hash)) {
      const result = await supabase.from('admin_users').update({ password_hash: hash, updated_at: new Date().toISOString() }).eq('id', row.id);
      if (result.error) throw result.error;
    } else if (row.is_active === false) {
      throw new Error('The configured administrator account is disabled.');
    }
    return;
  }
  const row = sqlite.prepare('SELECT * FROM admin_users WHERE username = ?').get(username); if (!row) sqlite.prepare('INSERT INTO admin_users (username,password_hash,role) VALUES (?,?,?)').run(username,bcrypt.hashSync(password,10),'admin'); else if (!bcrypt.compareSync(password,row.password_hash)) sqlite.prepare('UPDATE admin_users SET password_hash=? WHERE username=?').run(bcrypt.hashSync(password,10),username);
}
function mimeFromExt(ext) { return ({'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif','.mp4':'video/mp4','.webm':'video/webm','.mov':'video/quicktime','.mp3':'audio/mpeg','.m4a':'audio/mp4','.wav':'audio/wav','.ogg':'audio/ogg','.pdf':'application/pdf'})[ext] || 'application/octet-stream'; }
async function migrateSqliteIfPresent() {
  if (!useSupabase || !sqlite) return; console.log('Existing SQLite database found; starting one-time Supabase migration.');
  const content = sqlite.prepare('SELECT key,value FROM site_content').all(); if (content.length) { const { error } = await supabase.from('site_content').upsert(content, { onConflict: 'key' }); if (error) throw error; }
  const users = sqlite.prepare('SELECT username,password_hash,role FROM admin_users').all(); for (const user of users) { const existing = await supabase.from('admin_users').select('id').eq('username', user.username).maybeSingle(); if (existing.error) throw existing.error; if (!existing.data) { const inserted = await supabase.from('admin_users').insert(user); if (inserted.error) throw inserted.error; } }
  const media = sqlite.prepare('SELECT id,title,type,category,description,url,file_path,created_at FROM media_items ORDER BY id').all(); for (const item of media) { const existing = await supabase.from('media_items').select('id').eq('legacy_id', item.id).maybeSingle(); if (existing.error) throw existing.error; if (existing.data) continue; let url = item.url, storagePath = null; if (item.file_path && fs.existsSync(item.file_path)) { const ext = path.extname(item.file_path).toLowerCase() || '.bin'; storagePath = `migrated/${item.id}-${Date.now()}${ext}`; const blob = new Blob([fs.readFileSync(item.file_path)], { type: mimeFromExt(ext) }); const uploaded = await supabase.storage.from(STORAGE_BUCKET).upload(storagePath, blob, { contentType: mimeFromExt(ext), upsert: false }); if (uploaded.error) throw uploaded.error; url = supabase.storage.from(STORAGE_BUCKET).getPublicUrl(storagePath).data.publicUrl; } const inserted = await supabase.from('media_items').insert({ legacy_id: item.id, title: item.title, type: item.type, category: item.category, description: item.description || '', url, storage_path: storagePath, created_at: item.created_at }).select().single(); if (inserted.error) throw inserted.error; }
  console.log('SQLite migration completed successfully.');
}
async function dbGetAdmin(username) { if (useSupabase) return (await supabase.from('admin_users').select('*').eq('username', username).maybeSingle()).data; return sqlite.prepare('SELECT * FROM admin_users WHERE username=?').get(username); }
async function getSiteContent() { if (useSupabase) { const { data,error } = await supabase.from('site_content').select('key,value'); if(error) throw error; const payload={}; for(const row of data||[]) payload[row.key]=parseStoredValue(row.value); return mergeSiteContent(payload); } const payload={}; sqlite.prepare('SELECT key,value FROM site_content').all().forEach(({key,value})=>{payload[key]=parseStoredValue(value);}); return mergeSiteContent(payload); }
function safePublicUrl(value, { allowFragment = true } = {}) { const raw=String(value??'').trim(); if(!raw)return ''; if(allowFragment&&raw.startsWith('#'))return raw.slice(0,300); try{const url=new URL(raw,'https://local.invalid');if(url.origin==='https://local.invalid')return '';if(!['http:','https:'].includes(url.protocol))return '';return url.href.slice(0,2000);}catch(_){return '';} }
function sanitizeSiteContent(body={}) { const value={...body}; ['videoUrl','audioUrl','fallbackImage'].forEach(key=>{if(key in value)value[key]=safePublicUrl(value[key],{allowFragment:false});}); if(Array.isArray(value.links))value.links=value.links.map(item=>({...item,url:safePublicUrl(item?.url),image:safePublicUrl(item?.image,{allowFragment:false})})); if(Array.isArray(value.membershipClasses))value.membershipClasses=value.membershipClasses.map(item=>({...item,registrationUrl:safePublicUrl(item?.registrationUrl),image:safePublicUrl(item?.image,{allowFragment:false})})); if(Array.isArray(value.services))value.services=value.services.map(item=>({...item,image:safePublicUrl(item?.image,{allowFragment:false})})); if(Array.isArray(value.gallery))value.gallery=value.gallery.map(item=>({...item,src:safePublicUrl(item?.src,{allowFragment:false})})); if(value.liveStream&&typeof value.liveStream==='object')value.liveStream={...value.liveStream,url:safePublicUrl(value.liveStream.url,{allowFragment:false})}; if(value.theme&&typeof value.theme==='object')value.theme={...value.theme,accent:/^#[0-9a-f]{6}$/i.test(String(value.theme.accent||''))?value.theme.accent:undefined,mode:value.theme.mode==='dark'?'dark':'light'}; return value; }
async function saveSiteContent(body) { const cleanBody=sanitizeSiteContent(body||{}); const rows=Object.entries(cleanBody).map(([key,value])=>({key,value:typeof value==='string'?value:JSON.stringify(value)})); if(useSupabase){const{error}=await supabase.from('site_content').upsert(rows,{onConflict:'key'});if(error)throw error;return;} const update=sqlite.prepare('INSERT INTO site_content (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value'); sqlite.transaction(()=>rows.forEach(row=>update.run(row.key,row.value)))(); }
async function listMedia() { if(useSupabase){const{data,error}=await supabase.from('media_items').select('id,title,type,category,description,url,created_at').order('created_at',{ascending:false});if(error)throw error;return data||[];} return sqlite.prepare('SELECT id,title,type,category,description,url,created_at FROM media_items ORDER BY created_at DESC').all(); }
async function addMedia(item) { if(useSupabase){const{data,error}=await supabase.from('media_items').insert(item).select('id,title,type,category,description,url,created_at').single();if(error)throw error;return data;} const result=sqlite.prepare('INSERT INTO media_items (title,type,category,description,url,file_path) VALUES (?,?,?,?,?,?)').run(item.title,item.type,item.category,item.description,item.url,item.file_path||null);return{id:result.lastInsertRowid,title:item.title,type:item.type,category:item.category,description:item.description,url:item.url}; }
async function findMedia(id) { const numericId=Number(id);if(!Number.isSafeInteger(numericId)||numericId<1)return null;if(useSupabase)return(await supabase.from('media_items').select('*').eq('id',numericId).maybeSingle()).data;return sqlite.prepare('SELECT * FROM media_items WHERE id=?').get(numericId); }
async function updateMedia(id, changes) { const numericId=Number(id);if(!Number.isSafeInteger(numericId)||numericId<1)throw new Error('Invalid media id.'); const clean={title:String(changes.title??'').trim().slice(0,200),description:String(changes.description??'').trim().slice(0,2000),category:String(changes.category??'general').trim().slice(0,100)||'general'};if(!clean.title)throw new Error('Media title is required.');if(useSupabase){const{data,error}=await supabase.from('media_items').update(clean).eq('id',numericId).select('id,title,type,category,description,url,created_at').maybeSingle();if(error)throw error;return data||null;}const result=sqlite.prepare('UPDATE media_items SET title=?,description=?,category=? WHERE id=?').run(clean.title,clean.description,clean.category,numericId);if(!result.changes)return null;return sqlite.prepare('SELECT id,title,type,category,description,url,created_at FROM media_items WHERE id=?').get(numericId); }
async function removeMedia(id,item) { const numericId=Number(id);if(!Number.isSafeInteger(numericId)||numericId<1)throw new Error('Invalid media id.');if(useSupabase){if(item.storage_path){const removed=await supabase.storage.from(STORAGE_BUCKET).remove([item.storage_path]);if(removed.error)console.error('Storage delete failed:',removed.error);}const{error}=await supabase.from('media_items').delete().eq('id',numericId);if(error)throw error;return;}if(item.file_path&&fs.existsSync(item.file_path))fs.unlinkSync(item.file_path);sqlite.prepare('DELETE FROM media_items WHERE id=?').run(numericId); }
async function listLiveComments({ admin = false } = {}) { if(!useSupabase)return[];let query=supabase.from('live_comments').select('id,name,comment,approved,created_at').order('created_at',{ascending:false}).limit(200);if(!admin)query=query.eq('approved',true);const{data,error}=await query;if(error)throw error;return data||[]; }
async function addLiveComment(name,comment) { if(!useSupabase)throw new Error('Live comments require Supabase to be configured.');const cleanName=String(name||'').trim().slice(0,60);const cleanComment=String(comment||'').trim().slice(0,500);if(!cleanName||!cleanComment)throw new Error('Name and comment are required.');const{data,error}=await supabase.from('live_comments').insert({name:cleanName,comment:cleanComment,approved:true}).select('id,name,comment,approved,created_at').single();if(error)throw error;return data; }
async function moderateLiveComment(id,approved) { if(!useSupabase)throw new Error('Live comments require Supabase to be configured.');const numericId=Number(id);if(!Number.isSafeInteger(numericId)||numericId<1)throw new Error('Invalid comment id.');const{data,error}=await supabase.from('live_comments').update({approved:Boolean(approved)}).eq('id',numericId).select('id,name,comment,approved,created_at').single();if(error)throw error;return data; }
async function deleteLiveComment(id) { if(!useSupabase)throw new Error('Live comments require Supabase to be configured.');const numericId=Number(id);if(!Number.isSafeInteger(numericId)||numericId<1)throw new Error('Invalid comment id.');const{error}=await supabase.from('live_comments').delete().eq('id',numericId);if(error)throw error; }
function hasSignature(buffer,type) { if(!Buffer.isBuffer(buffer))return false; const ascii=(offset)=>buffer.subarray(offset,Math.min(buffer.length,offset+12)).toString('ascii'); if(type==='image/jpeg')return buffer.length>=3&&buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff; if(type==='image/png')return buffer.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])); if(type==='image/gif')return ascii(0).startsWith('GIF87a')||ascii(0).startsWith('GIF89a'); if(type==='image/webp')return ascii(0).startsWith('RIFF')&&ascii(8).startsWith('WEBP'); if(type==='application/pdf')return ascii(0).startsWith('%PDF-'); if(type==='video/mp4'||type==='video/quicktime'||type==='audio/mp4')return buffer.length>12&&ascii(4).includes('ftyp'); if(type==='video/webm')return buffer.length>=4&&buffer.subarray(0,4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3])); if(type==='audio/mpeg')return ascii(0).startsWith('ID3')||(buffer.length>=2&&buffer[0]===0xff&&(buffer[1]&0xe0)===0xe0); if(type==='audio/wav')return ascii(0).startsWith('RIFF')&&ascii(8).startsWith('WAVE'); if(type==='audio/ogg')return ascii(0).startsWith('OggS'); if(type==='audio/webm')return buffer.length>=4&&buffer.subarray(0,4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3])); return false; }

await initDatabase();
if(useSupabase)await migrateSqliteIfPresent();
await ensureAdminUser();
await ensureDefaultSiteContent();

const app=express();const port=process.env.PORT||3001;if(isProduction)app.set('trust proxy',1);app.disable('x-powered-by');
function reqIsApi(req){return req.path.startsWith('/api');}
app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(), usb=()');res.setHeader('Content-Security-Policy',"default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'; script-src 'self' 'unsafe-inline' https://www.youtube.com https://www.youtube-nocookie.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob: https:; media-src 'self' blob: https:; frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com; connect-src 'self' https://*.supabase.co https://www.youtube.com; worker-src 'self' blob:; manifest-src 'self'; upgrade-insecure-requests");if(reqIsApi(_req))res.setHeader('Cache-Control','no-store');if(isProduction)res.setHeader('Strict-Transport-Security','max-age=63072000; includeSubDomains');next();});
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true,limit:'1mb'}));app.use(session({secret:process.env.SESSION_SECRET||'development-only-session-secret',resave:false,saveUninitialized:false,name:isProduction?'__Host-kfc.sid':'kfc.sid',cookie:{maxAge:1000*60*60*12,httpOnly:true,sameSite:'strict',secure:isProduction,path:'/'}}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024,files:1,fields:20,parts:25},fileFilter:(_req,file,cb)=>new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime','audio/mpeg','audio/mp4','audio/wav','audio/ogg','audio/webm','application/pdf']).has(file.mimetype)?cb(null,true):cb(new Error('Unsupported file type. Upload an image, video, audio file, or PDF.'))});
function requireAdmin(req,res,next){if(!req.session.user)return res.status(401).json({error:'Unauthorized. Please log in.'});next();}
const securityBuckets=new Map();function rateLimit({windowMs,max,keyFn}){return(req,res,next)=>{const key=keyFn(req),now=Date.now(),old=securityBuckets.get(key);if(!old||now-old.startedAt>windowMs){securityBuckets.set(key,{startedAt:now,count:1});return next();}old.count+=1;if(old.count>max){res.setHeader('Retry-After',String(Math.ceil((old.startedAt+windowMs-now)/1000)));return res.status(429).json({error:'Too many requests. Please try again later.'});}next();};}
const unsafeLimiter=rateLimit({windowMs:5*60*1000,max:120,keyFn:req=>`unsafe:${req.ip}`});const loginLimiter=rateLimit({windowMs:15*60*1000,max:10,keyFn:req=>`login:${req.ip}:${String(req.body?.username||'').trim().toLowerCase()}`});const commentLimiter=rateLimit({windowMs:10*60*1000,max:5,keyFn:req=>`comment:${req.ip}`});
function requireSameOrigin(req,res,next){const method=req.method.toUpperCase();if(['POST','PUT','PATCH','DELETE'].includes(method)){const origin=req.get('Origin'),host=req.get('Host');if(!origin)return res.status(403).json({error:'Cross-site request blocked: an Origin header is required for state-changing requests.'});try{const originUrl=new URL(origin);if(originUrl.host!==host||!['http:','https:'].includes(originUrl.protocol))return res.status(403).json({error:'Cross-site request blocked.'});}catch(_error){return res.status(403).json({error:'Invalid request origin.'});}return unsafeLimiter(req,res,()=>{if(req.path==='/api/admin/login'||req.path==='/api/admin/activate')return loginLimiter(req,res,next);if(req.path==='/api/live/comments')return commentLimiter(req,res,next);next();});}next();}

registerAdminRbacRoutes({app,supabase,requireAdmin,requireSameOrigin});
const loginAttempts=new Map(),LOGIN_WINDOW_MS=15*60*1000,LOGIN_MAX_ATTEMPTS=10;function loginKey(req){return`${req.ip}:${String(req.body?.username||'').trim().toLowerCase()}`;}function isRateLimited(key){const entry=loginAttempts.get(key);if(!entry||Date.now()-entry.startedAt>LOGIN_WINDOW_MS){loginAttempts.delete(key);return false;}return entry.count>=LOGIN_MAX_ATTEMPTS;}function recordFailedLogin(key){const now=Date.now(),entry=loginAttempts.get(key);if(!entry||now-entry.startedAt>LOGIN_WINDOW_MS)loginAttempts.set(key,{startedAt:now,count:1});else entry.count+=1;}function clearLoginAttempts(key){loginAttempts.delete(key);}
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'aic-kitanga-admin',database:useSupabase?'supabase':'sqlite'}));
app.post('/api/admin/login',requireSameOrigin,async(req,res)=>{try{const{username,password}=req.body||{},key=loginKey(req);if(isRateLimited(key))return res.status(429).json({error:'Too many login attempts. Please try again later.'});const user=await dbGetAdmin(username);if(!user||user.is_active===false||!bcrypt.compareSync(password||'',user.password_hash)){recordFailedLogin(key);return res.status(401).json({error:'Invalid username or password.'});}clearLoginAttempts(key);if(useSupabase)await supabase.from('admin_users').update({last_login_at:new Date().toISOString()}).eq('id',user.id);req.session.regenerate(error=>{if(error)return res.status(500).json({error:'Unable to create a secure session.'});req.session.user={id:user.id,username:user.username,role:user.role};res.json({ok:true,user:req.session.user});});}catch(error){console.error(error);res.status(500).json({error:'Unable to log in.'});}});
app.post('/api/admin/logout',requireSameOrigin,(req,res)=>req.session.destroy(()=>{res.setHeader('Clear-Site-Data','"cache"');res.json({ok:true});}));
app.get('/api/admin/session',(req,res)=>{if(!req.session.user)return res.status(401).json({loggedIn:false});res.json({loggedIn:true,user:req.session.user});});
app.get('/api/site/content',async(_req,res)=>{try{res.json(await getSiteContent());}catch(error){console.error(error);res.status(500).json({error:'Unable to load site content.'});}});
app.put('/api/site/content',requireSameOrigin,requireAdmin,async(req,res)=>{try{await saveSiteContent(req.body||{});res.json({ok:true});}catch(error){console.error(error);res.status(500).json({error:'Unable to save site content.'});}});
app.get('/api/live/comments',async(_req,res)=>{try{res.json(await listLiveComments());}catch(error){console.error(error);res.status(500).json({error:'Unable to load live comments.'});}});
app.post('/api/live/comments',requireSameOrigin,async(req,res)=>{try{const item=await addLiveComment(req.body?.name,req.body?.comment);res.status(201).json(item);}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to post comment.'});}});
app.get('/api/admin/live/comments',requireAdmin,async(_req,res)=>{try{res.json(await listLiveComments({admin:true}));}catch(error){console.error(error);res.status(500).json({error:'Unable to load live comments.'});}});
app.patch('/api/admin/live/comments/:id',requireSameOrigin,requireAdmin,async(req,res)=>{try{const item=await moderateLiveComment(req.params.id,req.body?.approved);res.json(item);}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to update comment.'});}});
app.delete('/api/admin/live/comments/:id',requireSameOrigin,requireAdmin,async(req,res)=>{try{await deleteLiveComment(req.params.id);res.json({ok:true});}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to delete comment.'});}});
app.get('/api/media',async(_req,res)=>{try{res.json(await listMedia());}catch(error){console.error(error);res.status(500).json({error:'Unable to load media.'});}});
app.post('/api/media',requireSameOrigin,requireAdmin,upload.single('file'),async(req,res)=>{try{const file=req.file;if(!file)return res.status(400).json({error:'Please select a file to upload.'});if(!hasSignature(file.buffer,file.mimetype))return res.status(400).json({error:'The uploaded file content does not match its declared type.'});const{title,description,category,type}=req.body||{},inferredType=file.mimetype.startsWith('video/')?'video':file.mimetype.startsWith('audio/')?'audio':file.mimetype==='application/pdf'?'document':'image',mediaType=['image','video','audio','document'].includes(type)?type:inferredType;const cleanTitle=String(title||'').trim().slice(0,200)||path.basename(file.originalname,path.extname(file.originalname)).slice(0,200);const cleanDescription=String(description||'').trim().slice(0,2000);const cleanCategory=String(category||'general').trim().slice(0,100)||'general';if(useSupabase){const safeName=(file.originalname||'file').replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,120)||'file';const storagePath=`uploads/${Date.now()}-${Math.random().toString(16).slice(2)}-${safeName}`;const blob=new Blob([file.buffer],{type:file.mimetype});const uploaded=await supabase.storage.from(STORAGE_BUCKET).upload(storagePath,blob,{contentType:file.mimetype,cacheControl:'3600',upsert:false});if(uploaded.error)throw uploaded.error;const url=supabase.storage.from(STORAGE_BUCKET).getPublicUrl(storagePath).data.publicUrl;const item=await addMedia({title:cleanTitle,description:cleanDescription,category:cleanCategory,type:mediaType,url,storage_path:storagePath});return res.status(201).json(item);}const ext=path.extname(file.originalname||'').toLowerCase();const filename=`${Date.now()}-${Math.random().toString(16).slice(2)}${ext}`;const filePath=path.join(uploadDir,filename);fs.writeFileSync(filePath,file.buffer,{flag:'wx'});const item=await addMedia({title:cleanTitle,description:cleanDescription,category:cleanCategory,type:mediaType,url:`/uploads/${filename}`,file_path:filePath});res.status(201).json(item);}catch(error){console.error(error);res.status(500).json({error:error.message||'Upload failed.'});}});
app.patch('/api/media/:id',requireSameOrigin,requireAdmin,async(req,res)=>{try{const item=await updateMedia(req.params.id,req.body||{});if(!item)return res.status(404).json({error:'Media item not found.'});res.json(item);}catch(error){console.error(error);res.status(400).json({error:error.message||'Unable to update media.'});}});
app.delete('/api/media/:id',requireSameOrigin,requireAdmin,async(req,res)=>{try{const item=await findMedia(req.params.id);if(!item)return res.status(404).json({error:'Media item not found.'});await removeMedia(req.params.id,item);res.json({ok:true});}catch(error){console.error(error);res.status(500).json({error:'Delete failed.'});}});
const distPath=path.join(__dirname,'dist'),indexPath=path.join(distPath,'index.html');if(fs.existsSync(distPath))app.use(express.static(distPath));app.use('/admin',express.static(path.join(__dirname,'admin')));if(!useSupabase)app.use('/uploads',express.static(uploadDir,{fallthrough:true,setHeaders:(res)=>res.setHeader('X-Content-Type-Options','nosniff')}));app.get('/admin',(_req,res)=>res.sendFile(path.join(__dirname,'admin.html'));app.get(/^\/admin(?:\/.*)?$/,(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));app.use((req,res,next)=>{if(req.path.startsWith('/api')||req.path.startsWith('/uploads'))return next();res.sendFile(fs.existsSync(indexPath)?indexPath:path.join(__dirname,'index.html'));});app.use((err,_req,res,_next)=>{if(err instanceof multer.MulterError||err?.message?.startsWith('Unsupported file type'))return res.status(400).json({error:err.message});console.error(err);res.status(500).json({error:'Internal server error.'});});app.listen(port,'0.0.0.0',()=>console.log(`AIC Kitanga admin server running on http://0.0.0.0:${port} using ${useSupabase?'Supabase':'SQLite'}`));
