-- AIC Kitanga / Kingdom Fellowship Church site
-- Run this once in Supabase SQL Editor before deploying the app.

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text not null default 'admin'
);

create table if not exists public.site_content (
  key text primary key,
  value text not null
);

create table if not exists public.media_items (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  title text not null,
  type text not null,
  category text not null default 'general',
  description text default '',
  url text not null,
  storage_path text,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;
alter table public.media_items enable row level security;

insert into storage.buckets (id, name, public, file_size_limit)
values ('church-media', 'church-media', true, 52428800)
on conflict (id) do update set public = true, file_size_limit = 52428800;

drop policy if exists "Public church media read" on storage.objects;
create policy "Public church media read"
on storage.objects
for select
to public
using (bucket_id = 'church-media');
