-- Three-number administrator approval requests
-- Run this migration in Supabase SQL Editor.

create table if not exists public.admin_approval_requests (
  id bigint generated by default as identity primary key,
  username text not null,
  request_token_hash text unique not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  selected_option text,
  approved_option text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','expired','completed')),
  expires_at timestamptz not null,
  approved_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_approval_requests_status_idx
  on public.admin_approval_requests(status);
create index if not exists admin_approval_requests_expires_idx
  on public.admin_approval_requests(expires_at);
create index if not exists admin_approval_requests_username_idx
  on public.admin_approval_requests(username);

alter table public.admin_approval_requests enable row level security;

drop policy if exists "No direct client access to admin approval requests"
  on public.admin_approval_requests;

create policy "No direct client access to admin approval requests"
  on public.admin_approval_requests
  for all
  using (false)
  with check (false);
