-- Kingdom Fellowship Christian Church Supabase schema
-- Run this once in the Supabase SQL Editor before deploying the app.

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text not null default 'super_admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

-- Granular permissions for admin users. A super_admin bypasses this table.
create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.admin_users(id) on delete cascade,
  permission text not null,
  created_at timestamptz not null default now(),
  unique(user_id, permission)
);

-- Records administrative changes for accountability.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.admin_users(id) on delete set null,
  action text not null,
  resource text,
  resource_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_permissions_user_id_idx on public.admin_permissions(user_id);
create index if not exists admin_audit_log_user_id_idx on public.admin_audit_log(user_id);
create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log(created_at desc);

create table if not exists public.site_content (
  key text primary key,
  value text not null
);

create table if not exists public.media_items (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  title text not null,
  type text not null,
  category text not null default 'general',
  description text default '',
  url text not null,
  storage_path text,
  created_at timestamptz not null default now()
);

-- Live-page church family chat.
create table if not exists public.live_comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  comment text not null check (char_length(comment) between 1 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.admin_permissions enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.site_content enable row level security;
alter table public.media_items enable row level security;
alter table public.live_comments enable row level security;

-- Public visitors can only read approved live comments.
drop policy if exists "Public approved live comments read" on public.live_comments;
create policy "Public approved live comments read"
on public.live_comments
for select to anon, authenticated
using (approved = true);

insert into storage.buckets (id, name, public, file_size_limit)
values ('church-media', 'church-media', true, 52428800)
on conflict (id) do update set public = true, file_size_limit = 52428800;

drop policy if exists "Public church media read" on storage.objects;
create policy "Public church media read"
on storage.objects
for select
to public
using (bucket_id = 'church-media');

-- Existing administrator becomes the permanent Super Admin when this migration runs.
-- The UPDATE is intentionally role-only; it never changes the existing password.
update public.admin_users
set role = 'super_admin', is_active = true, updated_at = now()
where role = 'admin';
