(function(){
  'use strict';
  const types=['hero','text','image_text','gallery','cards','events','services','video','youtube','live','contact','cta','giving','custom'];
  const api=(url,opt={})=>window.adminApi?window.adminApi(url,opt):fetch(url,{credentials:'same-origin',...opt});
  const esc=value=>window.escSite?window.escSite(value):String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const message=(text,error=false)=>window.showAdminMessage?.(text,error);
  let pages=[],editing=null,navigation=[];
  function sectionRow(section,index){const content=section.content||{};return `<div class="editor-item cms-section-row" data-section="${index}"><div class="editor-head"><strong>Section ${index+1}</strong><div class="toolbar"><button type="button" class="secondary small" data-up="${index}" ${index?'':'disabled'}>Up</button><button type="button" class="secondary small" data-down="${index}" ${index<((editing?.sections||[]).length-1)?'':'disabled'}>Down</button><button type="button" class="danger small" data-remove="${index}">Remove</button></div></div><div class="grid"><div><label>Block type</label><select data-field="section_type">${types.map(type=>`<option value="${type}" ${section.section_type===type?'selected':''}>${type.replace('_',' + ')}</option>`).join('')}</select></div><div><label>Heading</label><input data-content="heading" value="${esc(content.heading||'')}"></div><div><label>Image or video URL</label><input data-content="media" type="url" value="${esc(content.media||content.image||content.url||'')}"></div></div><label>Body content</label><textarea data-content="body">${esc(content.body||content.text||'')}</textarea></div>`}
  function renderEditor(){const box=document.getElementById('cmsPageEditor');if(!box)return;if(!editing){box.innerHTML='';return}const page=editing;box.innerHTML=`<div class="grid"><div><label>Internal page name</label><input data-page="internal_name" value="${esc(page.internal_name)}" required></div><div><label>Page URL slug</label><input data-page="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="${esc(page.slug)}" required></div><div><label>Menu label</label><input data-page="menu_label" value="${esc(page.menu_label)}" required></div><div><label>Page status</label><select data-page="status"><option value="draft" ${page.status==='draft'?'selected':''}>Draft</option><option value="published" ${page.status==='published'?'selected':''}>Published</option><option value="archived" ${page.status==='archived'?'selected':''}>Archived</option></select></div></div><label><input data-page="show_in_navigation" type="checkbox" ${page.show_in_navigation?'checked':''} style="width:auto"> Show in navigation</label><div class="head"><div><h3>Page sections</h3><p class="muted">Build the page from structured blocks. Content is rendered safely by the public page view.</p></div><button type="button" class="secondary small" id="cmsAddSection">+ Add Section</button></div><div id="cmsSections">${(page.sections||[]).map(sectionRow).join('')||'<div class="empty">No sections yet.</div>'}</div><div class="toolbar" style="margin-top:14px"><button type="button" class="secondary" id="cmsCancel">Cancel</button><button type="button" class="primary" id="cmsSave">Save Page</button></div>`;
    box.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('input',()=>{editing[el.dataset.page]=el.type==='checkbox'?el.checked:el.value}));
    box.querySelector('#cmsAddSection')?.addEventListener('click',()=>{editing.sections=editing.sections||[];editing.sections.push({section_type:'text',content:{}});renderEditor()});
    box.querySelector('#cmsCancel')?.addEventListener('click',()=>{editing=null;render()});
    box.querySelector('#cmsSave')?.addEventListener('click',savePage);
    box.querySelectorAll('[data-content],[data-field]').forEach(el=>el.addEventListener('input',()=>{const row=el.closest('[data-section]'),section=editing.sections[Number(row.dataset.section)];if(el.dataset.field)section[el.dataset.field]=el.value;else section.content[el.dataset.content]=el.value}));
    box.querySelectorAll('[data-remove]').forEach(el=>el.addEventListener('click',()=>{editing.sections.splice(Number(el.dataset.remove),1);renderEditor()}));
    box.querySelectorAll('[data-up],[data-down]').forEach(el=>el.addEventListener('click',()=>{const index=Number(el.dataset.up??el.dataset.down),next=el.dataset.up?index-1:index+1;[editing.sections[index],editing.sections[next]]=[editing.sections[next],editing.sections[index]];renderEditor()}));
  }
  function renderList(){const box=document.getElementById('cmsPagesList');if(!box)return;box.innerHTML=pages.length?pages.map(page=>`<div class="editor-item"><div class="editor-head"><div><strong>${esc(page.internal_name)}</strong><span class="status ${page.status==='published'?'ok':''}">${esc(page.status)}</span><p class="muted">/${esc(page.slug)} · ${page.sections?.length||0} sections</p></div><div class="toolbar"><button type="button" class="secondary small" data-edit="${page.id}">Edit</button><button type="button" class="danger small" data-delete="${page.id}">Delete</button></div></div></div>`).join(''):'<div class="empty">No pages yet. Create the first page below.</div>';box.querySelectorAll('[data-edit]').forEach(button=>button.addEventListener('click',()=>{editing=JSON.parse(JSON.stringify(pages.find(page=>String(page.id)===button.dataset.edit)));render()}));box.querySelectorAll('[data-delete]').forEach(button=>button.addEventListener('click',()=>deletePage(button.dataset.delete)))}
  function renderNavigation(){const box=document.getElementById('cmsNavigationList');if(!box)return;box.innerHTML=navigation.length?navigation.map((item,index)=>`<div class="editor-item grid"><div><label>Label</label><input data-nav="label" data-index="${index}" value="${esc(item.label)}"></div><div><label>URL</label><input data-nav="href" data-index="${index}" value="${esc(item.href)}"></div><div><label>Parent menu</label><select data-nav="parent_index" data-index="${index}"><option value="">Top level</option>${navigation.map((parent,parentIndex)=>parentIndex!==index?`<option value="${parentIndex}" ${Number(item.parent_index)===parentIndex?'selected':''}>${esc(parent.label||'Menu '+(parentIndex+1))}</option>`:'').join('')}</select></div><div><label>Position</label><input data-nav="position" data-index="${index}" type="number" min="0" value="${Number(item.position)||0}"></div><button type="button" class="danger small" data-nav-remove="${index}">Remove</button></div>`).join(''):'<div class="empty">No navigation items yet.</div>';box.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('input',()=>{navigation[Number(el.dataset.index)][el.dataset.nav]=el.dataset.nav==='parent_index'?(el.value===''?null:Number(el.value)):el.type==='number'?Number(el.value):el.value}));box.querySelectorAll('[data-nav-remove]').forEach(el=>el.addEventListener('click',()=>{navigation.splice(Number(el.dataset.navRemove),1);navigation.forEach(item=>{if(item.parent_index===Number(el.dataset.navRemove))item.parent_index=null});renderNavigation()}))}
  async function load(){try{const[pageResponse,navResponse]=await Promise.all([api('/api/cms/pages'),api('/api/cms/admin/navigation')]);if(!pageResponse.ok)throw new Error('Unable to load CMS pages.');pages=await pageResponse.json();navigation=navResponse.ok?await navResponse.json():[];render()}catch(error){message(error.message,true)}}
  async function savePage(){const body={...editing,sections:(editing.sections||[]).map((section,position)=>({...section,position}))};const response=await api(editing.id?`/api/cms/pages/${editing.id}`:'/api/cms/pages',{method:editing.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){message((await response.json()).error||'Unable to save page.',true);return}message('Page saved.');editing=null;await load()}
  async function deletePage(id){if(!confirm('Delete this page and its sections?'))return;const response=await api(`/api/cms/pages/${id}`,{method:'DELETE'});if(!response.ok){message('Unable to delete page.',true);return}await load()}
  async function saveNavigation(){const response=await api('/api/cms/navigation',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(navigation)});if(!response.ok){message((await response.json()).error||'Unable to save navigation.',true);return}navigation=await response.json();message('Navigation saved.');renderNavigation()}
  function render(){renderList();renderNavigation();renderEditor()}
  function install(){const target=document.getElementById('pages');if(!target||target.dataset.cmsReady)return;target.dataset.cmsReady='true';target.innerHTML='<div class="head"><div><h2>Pages</h2><p class="muted">Create published or draft pages from reusable sections.</p></div><button type="button" class="primary" id="cmsNewPage">Add New Page</button></div><div id="cmsPagesList"></div><div id="cmsPageEditor"></div><div class="head" style="margin-top:24px"><div><h2>Header & Navigation</h2><p class="muted">Manage the visible global menu used by the public site.</p></div><button type="button" class="primary" id="cmsSaveNavigation">Save Navigation</button></div><div id="cmsNavigationList"></div><button type="button" class="secondary small" id="cmsAddNavigation">+ Add Menu Item</button>';target.querySelector('#cmsNewPage').addEventListener('click',()=>{editing={internal_name:'',slug:'',menu_label:'',status:'draft',show_in_navigation:false,sections:[]};renderEditor()});target.querySelector('#cmsAddNavigation').addEventListener('click',()=>{navigation.push({label:'',href:'/',position:navigation.length,is_visible:true});renderNavigation()});target.querySelector('#cmsSaveNavigation').addEventListener('click',saveNavigation);load()}
  window.loadCms=load;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();