(function(){
  const mount=document.getElementById('adminHeader');
  if(!mount)return;
  window.__ADMIN_BUILD_VERSION=Date.now().toString();
  if(!document.querySelector('link[data-admin-header-css]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/admin/admin-header.css?v='+encodeURIComponent(window.__ADMIN_BUILD_VERSION);link.dataset.adminHeaderCss='true';document.head.appendChild(link)}
  if(!document.getElementById('admin-savebar-mobile-style')){const st=document.createElement('style');st.id='admin-savebar-mobile-style';st.textContent='@media(max-width:650px){#site .savebar{position:fixed!important;left:10px!important;right:10px!important;bottom:calc(10px + env(safe-area-inset-bottom,0px))!important;width:auto!important;margin:0!important;z-index:1100!important;display:flex!important;flex-direction:column!important;gap:8px!important;padding:10px!important;background:#fff!important;border:1px solid #dfe4e8!important;border-radius:12px!important;box-shadow:0 8px 30px #0003!important}#site .savebar .toolbar{width:100%!important;display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important}#site .savebar .toolbar button{width:100%!important;min-height:44px!important}}';document.head.appendChild(st)}
  mount.innerHTML='<header class="admin-header"><strong class="admin-header__title" data-admin-header-brand>Kingdom Fellowship Christian Church — Admin</strong><div class="admin-header__actions"><span id="apiStatus" class="admin-header__status">Checking…</span><a class="secondary small admin-header__back" href="/" aria-label="Back to website">← Back to Website</a><button id="adminLogout" class="secondary small" type="button" onclick="logout()" hidden>Log out</button></div></header>';
  const stepIcons=['<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/><circle cx="7" cy="7" r="1"/><circle cx="7" cy="12" r="1"/><circle cx="7" cy="17" r="1"/></svg>','<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>','<svg viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3.4 8-8 9-4.6-1-8-4-8-9V6l8-3Z"/><path d="m9 12 2 2 4-4"/></svg>','<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>'];
  const loading=document.createElement('div');loading.id='adminModuleLoading';loading.setAttribute('role','status');loading.setAttribute('aria-live','polite');loading.innerHTML='<div class="admin-module-loading-card"><div class="admin-module-logo-placeholder" data-logo-placeholder aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3v18M6 9l6-6 6 6M5 21h14M8 21V11h8v10"/><path d="M7 16h10"/></svg></div><img class="admin-module-logo" data-admin-logo alt="Church logo"><h1 class="admin-module-brand" data-admin-brand>Kingdom Fellowship Christian Church</h1><div class="admin-module-divider"></div><p class="admin-module-tagline" data-admin-tagline>Revealing Christ to Nations</p><h2 class="admin-module-title" data-loading-text>Loading Administration…</h2><p class="admin-module-subtitle" data-loading-subtitle>Preparing your workspace</p><div class="admin-module-dots"><span class="admin-module-dot active"></span><span class="admin-module-dot"></span><span class="admin-module-dot"></span><span class="admin-module-dot"></span></div><div class="admin-module-steps">'+[0,1,2,3].map((i)=>'<div class="admin-module-step" data-loading-step="'+i+'"><span class="admin-module-step-icon">'+stepIcons[i]+'</span><span>'+['Connecting<br>to server…','Initializing<br>components…','Checking<br>permissions…','Almost ready…'][i]+'</span></div>').join('')+'</div><p class="admin-module-quote">“For God gives wisdom…” <span>James 1:5</span></p><p class="admin-module-error" data-loading-error hidden></p><button class="admin-module-retry" data-loading-retry type="button">Retry connection</button></div>';document.body.appendChild(loading);
  function setLoadingStep(message){const text=document.querySelector('[data-loading-text]'),subtitle=document.querySelector('[data-loading-subtitle]'),dots=[...document.querySelectorAll('.admin-module-dot')],steps=[...document.querySelectorAll('.admin-module-step')],value=String(message||'Loading Administration…'),lower=value.toLowerCase();let index=0;if(lower.includes('access')||lower.includes('permission'))index=2;else if(lower.includes('section')||lower.includes('components')||lower.includes('modules'))index=3;else if(lower.includes('initial')||lower.includes('admin panel'))index=1;if(lower.includes('unable'))index=3;if(text)text.textContent=value;if(subtitle)subtitle.textContent=index===0?'Connecting to the administration service':index===1?'Initializing your administration workspace':index===2?'Verifying your administrator permissions':'Preparing your permitted sections';dots.forEach((d,i)=>{d.classList.toggle('active',i===index);d.classList.toggle('done',i<index)});steps.forEach((s,i)=>{s.classList.toggle('active',i===index);s.classList.toggle('done',i<index)})}window.setAdminLoadingState=setLoadingStep;
  function isImageMedia(item){if(!item||typeof item!=='object')return false;const type=String(item.type||item.mimeType||item.mime||'').toLowerCase();const url=String(item.url||item.src||item.path||item.fileUrl||'').toLowerCase().split('?')[0].split('#')[0];const imageType=type==='image'||type.startsWith('image/');const imageExtension=/\.(png|jpe?g|webp|gif|svg|avif|bmp|ico|tiff?)$/.test(url);return imageType||imageExtension}
  function mediaIsLogo(item){if(!item||!isImageMedia(item))return false;const category=String(item.category||item.mediaCategory||item.folder||'').toLowerCase().trim();const name=String(item.name||item.filename||item.fileName||item.title||'').toLowerCase();return category==='logo'||category.includes('logo')||name.includes('logo')}
  window.loadAdminBranding=async function(){try{const [r,m]=await Promise.all([fetch('/api/site/content',{credentials:'same-origin',cache:'no-store'}).catch(()=>null),fetch('/api/media',{credentials:'same-origin',cache:'no-store'}).catch(()=>null)]);const content=r?.ok?await r.json().catch(()=>({})):{};const media=m?.ok?await m.json().catch(()=>[]):[];const mediaItems=Array.isArray(media)?media:(Array.isArray(media?.items)?media.items:Array.isArray(media?.media)?media.media:[]);const mediaLogo=mediaItems.find(mediaIsLogo)||mediaItems.find(isImageMedia);const brand=document.querySelector('[data-admin-brand]'),tagline=document.querySelector('[data-admin-tagline]'),headerBrand=document.querySelector('[data-admin-header-brand]');if(brand&&content.churchName)brand.textContent=content.churchName;if(tagline&&content.tagline)tagline.textContent=content.tagline;if(headerBrand&&content.churchName)headerBrand.textContent=content.churchName+' — Admin';const logoUrl=mediaLogo?.url||mediaLogo?.src||mediaLogo?.path||mediaLogo?.fileUrl||content.logoUrl||content.logo||content.churchLogo;const img=document.querySelector('[data-admin-logo]'),placeholder=document.querySelector('[data-logo-placeholder]');if(img&&logoUrl){img.onload=()=>{img.classList.add('is-ready');if(placeholder)placeholder.hidden=true};img.onerror=()=>{img.removeAttribute('src');if(placeholder)placeholder.hidden=false};img.src=String(logoUrl)}if(content.fallbackImage)loading.style.backgroundImage='url("'+String(content.fallbackImage).replace(/"/g,'\\"')+'")';return content}catch(e){return {}}};
  loadAdminBranding();
  window.setAdminAuthenticatedUI=function(authenticated){const b=document.getElementById('adminLogout');if(b)b.hidden=!authenticated;document.body.classList.toggle('admin-authenticated',!!authenticated)};
  function installPasswordToggles(){document.querySelectorAll('input[type="password"]').forEach(input=>{if(input.dataset.passwordToggleReady)return;input.dataset.passwordToggleReady='true';const wrap=document.createElement('div');wrap.className='admin-password-wrap';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const b=document.createElement('button');b.type='button';b.className='admin-password-toggle';b.textContent='Show';b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Hide':'Show'};wrap.appendChild(b)})}installPasswordToggles();new MutationObserver(installPasswordToggles).observe(document.body,{childList:true,subtree:true});
  const load=()=>{const s=document.createElement('script');s.src='/admin/admin-loader.js?v='+encodeURIComponent(window.__ADMIN_BUILD_VERSION);s.dataset.adminModule='admin-loader.js';s.onload=()=>window.loadAdminModules?.().catch(console.error);s.onerror=()=>{setLoadingStep('Unable to load the admin loader. Please refresh and try again.');const e=document.querySelector('[data-loading-error]');if(e){e.hidden=false;e.textContent='The administration modules could not be loaded.'}};document.head.appendChild(s)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
