/* Admin Users & Permissions module. */
(function () {
  'use strict';
  const PERMISSIONS = {
    Site: { view:'View website content', edit:'Edit website content' },
    Media: { view:'View media', upload:'Upload media', edit:'Edit media', delete:'Delete media' },
    Comments: { view:'View comments', moderate:'Moderate comments' },
    Live: { view:'View live content', edit:'Edit live content' },
    Theme: { view:'View theme settings', edit:'Edit theme settings' },
    Users: { view:'View administrators', create:'Create administrators', edit:'Edit administrators', disable:'Enable/disable administrators', delete:'Delete administrators', permissions:'Manage permissions' },
    Audit: { view:'View audit log' }
  };
  const ROLES={content_editor:'Content Editor',media_manager:'Media Manager',live_manager:'Live Manager',custom:'Custom Permissions',super_admin:'Super Admin'};
  let currentUser=null;
  async function request(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
  function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function isSuperAdmin(){return currentUser?.role==='super_admin';}
  function hasPermission(p){return isSuperAdmin()||(Array.isArray(currentUser?.permissions)&&currentUser.permissions.includes(p));}
  function permissionEditor(selected=[]){const chosen=new Set(selected);return Object.entries(PERMISSIONS).map(([group,items])=>`<fieldset class="rbac-group"><legend>${esc(group)}</legend><div class="rbac-permission-grid">${Object.entries(items).map(([key,label])=>{const p=group.toLowerCase()+'.'+key;return `<label class="rbac-permission"><input type="checkbox" data-permission="${p}" ${chosen.has(p)?'checked':''}><span>${esc(label)}</span></label>`;}).join('')}</div></fieldset>`).join('');}
  function collectPermissions(c){return [...c.querySelectorAll('[data-permission]:checked')].map(e=>e.dataset.permission);}
  function roleOptions(selected){return Object.entries(ROLES).map(([v,l])=>`<option value="${v}" ${selected===v?'selected':''}>${l}</option>`).join('');}
  async function loadUsers(){const list=document.getElementById('adminUsersList');if(!list||!hasPermission('users.view'))return;list.innerHTML='<div class="empty">Loading administrators…</div>';try{const data=await request('/api/admin/users');const users=Array.isArray(data)?data:(Array.isArray(data.users)?data.users:[]);list.innerHTML=users.length?users.map(u=>`<div class="admin-user-row"><div class="admin-user-info"><strong>${esc(u.username)}</strong><div class="meta">${esc(ROLES[u.role]||u.role)} · <span class="rbac-status ${u.is_active?'active':'inactive'}">${u.is_active?'Active':'Disabled'}</span> · Last login: ${u.last_login_at?esc(new Date(u.last_login_at).toLocaleString()):'Never'}</div></div><div class="toolbar">${isSuperAdmin()?`<button type="button" class="secondary small" data-edit="${u.id}">Manage</button>`:''}${u.role!=='super_admin'&&isSuperAdmin()?`<button type="button" class="secondary small" data-status="${u.id}" data-active="${u.is_active}">${u.is_active?'Disable':'Enable'}</button><button type="button" class="danger small" data-delete="${u.id}">Delete</button>`:''}</div></div>`).join(''):'<div class="empty">No administrators found.</div>';list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editUser(+b.dataset.edit,users));list.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>toggleStatus(+b.dataset.status,b.dataset.active==='true'));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteUser(+b.dataset.delete));}catch(e){list.innerHTML=`<div class="empty">${esc(e.message)}</div>`;}}
  async function editUser(id,users){const u=users.find(x=>+x.id===id);if(!u)return;const username=prompt('Username:',u.username);if(username===null)return;const role=prompt('Role (super_admin, content_editor, media_manager, live_manager, or custom):',u.role);if(role===null)return;try{await request(`/api/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({username,role})});await loadUsers();alert('Administrator updated.');}catch(e){alert(e.message);}}
  async function toggleStatus(id,active){try{await request(`/api/admin/users/${id}/status`,{method:'PATCH',body:JSON.stringify({is_active:!active})});await loadUsers();}catch(e){alert(e.message);}}
  async function deleteUser(id){if(!confirm('Delete this administrator permanently?'))return;try{await request(`/api/admin/users/${id}`,{method:'DELETE'});await loadUsers();}catch(e){alert(e.message);}}
  async function createUser(e){e.preventDefault();const f=e.currentTarget;try{const created=await request('/api/admin/users',{method:'POST',body:JSON.stringify({username:f.username.value,password:f.password.value,role:f.role.value})});if(created.user?.id){const permissions=collectPermissions(f);if(permissions.length)await request(`/api/admin/users/${created.user.id}/permissions`,{method:'PUT',body:JSON.stringify({permissions})});}f.reset();f.querySelectorAll('[data-permission]').forEach(x=>x.checked=false);await loadUsers();alert('Administrator created.');}catch(err){alert(err.message);}}
  function styles(){if(document.getElementById('admin-rbac-styles'))return;const s=document.createElement('style');s.id='admin-rbac-styles';s.textContent=`#adminRbac{margin-top:24px}.rbac-account-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.rbac-group{border:1px solid var(--line);border-radius:12px;padding:14px;margin:14px 0}.rbac-group legend{font-weight:700;padding:0 7px}.rbac-permission-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px 18px}.rbac-permission{display:flex!important;align-items:center;gap:9px;width:auto!important;margin:0!important;padding:8px;border-radius:8px}.rbac-permission:hover{background:rgba(127,127,127,.08)}.rbac-permission input{width:18px!important;height:18px!important;margin:0}.rbac-status.active{font-weight:700}.rbac-status.inactive{font-weight:700}.admin-user-row{display:flex;justify-content:space-between;align-items:center;gap:16px;border-top:1px solid var(--line);padding:16px 0}.admin-user-row:first-child{border-top:0}.admin-user-info{min-width:0}.rbac-hidden{display:none!important}.rbac-role-note{padding:10px 12px;border-radius:8px;background:rgba(127,127,127,.08);margin:10px 0}.rbac-section-title{margin-top:18px}@media(max-width:650px){.admin-user-row{align-items:flex-start;flex-direction:column}.admin-user-row .toolbar{width:100%}}`;document.head.appendChild(s);}
  function ui(){if(document.getElementById('adminRbac'))return;const app=document.getElementById('app');if(!app)return;const w=document.createElement('div');w.id='adminRbac';w.innerHTML=`<section class="card" data-rbac-account><div class="head"><div><h2>My Account</h2><p class="muted">Manage your administrator username and password.</p></div></div><form id="myAccountForm"><div class="rbac-account-grid"><div><label>Username</label><input id="myAccountUsername" name="username" required></div><div><label>New password</label><input name="password" type="password" minlength="10" placeholder="Leave blank to keep current password"></div></div><div class="toolbar" style="margin-top:14px"><button class="primary">Save My Account</button></div></form></section><section class="card" data-rbac-users><div class="head"><div><h2>Users & Permissions</h2><p class="muted">Manage administrator accounts and their access.</p></div><button type="button" class="secondary small" id="refreshAdminUsers">Refresh</button></div><div id="adminUsersList"><div class="empty">Loading administrators…</div></div></section><section class="card" data-rbac-users-create><div class="head"><div><h2>Add Administrator</h2><p class="muted">Choose a role, then fine-tune its permissions.</p></div></div><form id="createAdminForm"><div class="rbac-account-grid"><div><label>Username</label><input name="username" required autocomplete="off"></div><div><label>Password</label><input name="password" type="password" minlength="10" required autocomplete="new-password"></div><div><label>Role</label><select name="role">${roleOptions('custom')}</select></div></div><div class="rbac-role-note"><strong>Tip:</strong> Custom Permissions lets you select exactly what this administrator can access.</div><h3 class="rbac-section-title">Permissions</h3>${permissionEditor()}<button class="primary" style="margin-top:10px">Create Administrator</button></form></section>`;app.appendChild(w);document.getElementById('createAdminForm').onsubmit=createUser;document.getElementById('refreshAdminUsers').onclick=loadUsers;document.getElementById('myAccountForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await request('/api/admin/me',{method:'PATCH',body:JSON.stringify({username:f.username.value,password:f.password.value||undefined})});alert('Account updated. Please sign in again if your username changed.');}catch(err){alert(err.message);}};}
  function applyPermissionsToUI(){const map=[['media','media.view'],['comments','comments.view'],['site','site.view']];map.forEach(([tab,p])=>{const b=document.querySelector(`.admin-navigation [data-tab="${tab}"]`);if(b)b.classList.toggle('rbac-hidden',!hasPermission(p));});const users=document.querySelector('[data-rbac-users]'),create=document.querySelector('[data-rbac-users-create]');if(users)users.classList.toggle('rbac-hidden',!hasPermission('users.view'));if(create)create.classList.toggle('rbac-hidden',!hasPermission('users.create'));}
  async function init(){styles();ui();try{const me=await request('/api/admin/me');currentUser=me.user;const input=document.getElementById('myAccountUsername');if(input)input.value=currentUser.username;applyPermissionsToUI();await loadUsers();}catch(e){console.error('Admin RBAC initialization failed:',e);}}
  window.AdminRBAC={init,loadUsers,hasPermission};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
