(function(){
'use strict';
const $=id=>document.getElementById(id);
const api=(url,opt={})=>window.adminApi?window.adminApi(url,opt):fetch(url,{credentials:'include',cache:'no-store',...opt});
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const categories=['general','hero','logo','gallery','services','about','events','resources','sermons','youth','worship','documents','other'];
const state={items:[],query:'',type:'all',category:'all',sort:'newest',view:'grid',uploadFiles:[]};
const notify=(t,e=false)=>window.showAdminMessage?.(t,e);
const readError=async(r,f)=>{try{return (await r.json())?.error||f}catch{return f}};
const typeLabel=t=>({image:'Image',video:'Video',audio:'Audio',document:'PDF'}[t]||'Media');
const date=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
function ensureCss(){if(document.querySelector('link[data-admin-media-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/admin/admin-media.css?v='+(window.__ADMIN_BUILD_VERSION||Date.now());l.dataset.adminMediaCss='true';document.head.appendChild(l)}
function normalize(data){return Array.isArray(data)?data:(Array.isArray(data?.items)?data.items:Array.isArray(data?.media)?data.media:[])}
function filtered(){let a=state.items.filter(x=>{const q=state.query.toLowerCase();return(!q||[x.title,x.description,x.category,x.type].join(' ').toLowerCase().includes(q))&&(state.type==='all'||x.type===state.type)&&(state.category==='all'||String(x.category||'general').toLowerCase()===state.category)});a.sort((x,y)=>state.sort==='name'?(x.title||'').localeCompare(y.title||''):state.sort==='oldest'?new Date(x.created_at||0)-new Date(y.created_at||0):new Date(y.created_at||0)-new Date(x.created_at||0));return a}
function preview(x){if(x.type==='image')return `<img src="${esc(x.url)}" alt="${esc(x.title)}" loading="lazy">`;if(x.type==='video')return `<video src="${esc(x.url)}" controls preload="metadata"></video>`;if(x.type==='audio')return `<audio src="${esc(x.url)}" controls preload="metadata"></audio>`;return '<div class="am-file-icon">PDF</div>'}
function card(x){const f=x.type==='video'&&x.featured===true;return `<article class="am-card${f?' am-card-featured':''}><div class="am-preview">${preview(x)}<span class="am-type">${esc(typeLabel(x.type))}</span>${f?'<span class="am-featured-badge">★ Featured Video</span>':''}</div><div class="am-card-body"><div class="am-card-title">${esc(x.title)}</div><div class="am-card-meta">${esc(x.category||'general')} · ${esc(date(x.created_at))} · ${x.published===false?'Draft':'Published'}</div><div class="am-card-desc">${esc(x.description||'No description added.')}</div><div class="am-card-actions"><button class="secondary small" type="button" data-copy="${esc(x.url)}">Copy URL</button><button class="secondary small" type="button" data-edit-id="${Number(x.id)}">Edit</button><button class="danger small" type="button" data-delete="${Number(x.id)}">Delete</button></div></div></article>`}
function render(){const box=$('mediaList');if(!box)return;const items=filtered();box.className=state.view==='list'?'am-list':'am-library';box.innerHTML=items.length?items.map(card).join(''):`<div class="am-empty"><strong>${state.items.length?'No matching media':'Your media library is empty'}</strong><span>${state.items.length?'Try another search or filter.':'Upload your first photo, video, audio file or PDF above.'}</span></div>`;box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyUrl(b.dataset.copy,b));box.querySelectorAll('[data-edit-id]').forEach(b=>b.onclick=()=>openMediaEditor(state.items.find(x=>Number(x.id)===Number(b.dataset.editId))));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>delMedia(Number(b.dataset.delete)));const r=$('amResultText');if(r)r.textContent=`Showing ${items.length} of ${state.items.length} media ${items.length===1?'item':'items'}.`}
function shell(){const root=$('media');if(!root)return;root.innerHTML=`<div class="am-shell"><section class="am-hero"><div><h2>Media Center</h2><p>Upload, organize and publish the church's photos, videos, audio and documents.</p></div><div id="amStats" class="am-stats"></div></section><section class="card"><div class="am-section-head"><div><h3>Upload media</h3><p>Upload media and choose whether a video should be the Featured Video.</p></div></div><form id="amUploadForm"><div id="amDrop" class="am-drop"><div class="am-drop-icon">↥</div><strong>Drop media here</strong><p>Images, videos, audio and PDFs are supported. Maximum file size is 50 MB.</p><button class="secondary small" type="button" id="amChoose">Choose file</button><input id="amFile" type="file" accept="image/*,video/*,audio/*,application/pdf"></div><div class="am-upload-meta"><label>Title<input id="amUploadTitle" maxlength="200" required></label><label>Category<select id="amUploadCategory">${categories.map(c=>`<option>${c}</option>`).join('')}</select></label></div><label>Description<textarea id="amUploadDescription" maxlength="2000"></textarea></label><div class="am-inline-grid"><label>Visibility<select id="amUploadPublished"><option value="published">Published</option><option value="draft">Draft</option></select></label><label class="am-featured-option"><span>Featured video</span><span><input id="amUploadFeatured" type="checkbox"> <strong>Set as Featured Video</strong></span><small>Only video files can be featured. This replaces the current featured video.</small></label></div><div class="am-upload-actions"><button class="primary" type="submit" id="amUploadButton">Upload media</button></div><div id="amFileStatus" class="am-status">No file selected.</div></form></section><section class="card"><div class="am-section-head"><div><h3>Media Library</h3><p id="amResultText">Browse every uploaded asset.</p></div><button class="secondary small" type="button" id="amRefresh">Refresh</button></div><div class="am-toolbar"><div class="am-search"><input id="amSearch" placeholder="Search media by title, category or description…"></div><select id="amType" class="am-filter"><option value="all">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">PDFs</option></select><select id="amCategory" class="am-filter"><option value="all">All categories</option>${categories.map(c=>`<option value="${c}">${c}</option>`).join('')}</select><select id="amSort" class="am-filter"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select><div class="am-view"><button type="button" id="amGrid" class="active">▦ Grid</button><button type="button" id="amList">☰ List</button></div></div><div id="mediaList" class="am-library"><div class="am-empty">Loading media…</div></div></section></div>`;bind()}
function bind(){const file=$('amFile'),drop=$('amDrop');$('amChoose').onclick=()=>file.click();file.onchange=()=>setFiles(file.files);drop.addEventListener('drop',e=>{e.preventDefault();setFiles(e.dataTransfer.files)});['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));$('amUploadForm').onsubmit=upload;$('amRefresh').onclick=loadMedia;$('amSearch').oninput=e=>{state.query=e.target.value;render()};$('amType').onchange=e=>{state.type=e.target.value;render()};$('amCategory').onchange=e=>{state.category=e.target.value;render()};$('amSort').onchange=e=>{state.sort=e.target.value;render()};$('amGrid').onclick=()=>{state.view='grid';$('amGrid').classList.add('active');$('amList').classList.remove('active');render()};$('amList').onclick=()=>{state.view='list';$('amList').classList.add('active');$('amGrid').classList.remove('active');render()};$('amUploadFeatured').onchange=updateFeaturedUpload;setTimeout(updateFeaturedUpload,0);ensureModalControl()}
function setFiles(files){state.uploadFiles=files?.length?[files[0]]:[];const f=state.uploadFiles[0];$('amFileStatus').textContent=f?`${f.name} · ${(f.size/1024/1024).toFixed(1)} MB`:'No file selected.';if(f&&!$('amUploadTitle').value)$('amUploadTitle').value=f.name.replace(/\.[^.]+$/,'').slice(0,200);updateFeaturedUpload()}
function updateFeaturedUpload(){const input=$('amUploadFeatured'),f=state.uploadFiles[0]||$('amFile')?.files?.[0];if(!input)return;const ok=Boolean(f&&String(f.type||'').toLowerCase().startsWith('video/'));input.disabled=!ok;if(!ok)input.checked=false;input.closest('.am-featured-option')?.classList.toggle('disabled',!ok)}
function ensureModalControl(){const form=$('mediaModal')?.querySelector('form');if(!form||$('mediaFeaturedOption'))return;const wrap=document.createElement('div');wrap.id='mediaFeaturedOption';wrap.className='am-featured-option';wrap.innerHTML='<span>Featured video</span><span><input id="mediaModalFeatured" type="checkbox"> <strong>Show this as Featured Video</strong></span><small>Only videos can be featured. This replaces the current featured video.</small>';const cat=$('editMediaCategory');cat?.parentNode?.insertBefore(wrap,cat.nextSibling)}
async function loadMedia(){ensureCss();shell();try{const r=await api('/api/media',{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw new Error(await readError(r,'Unable to load media.'));state.items=normalize(await r.json());const stats=$('amStats');if(stats){const videos=state.items.filter(x=>x.type==='video').length;stats.innerHTML=`<div class="am-stat"><strong>${state.items.length}</strong><span>Library items</span></div><div class="am-stat"><strong>${state.items.filter(x=>x.type==='image').length}</strong><span>Images</span></div><div class="am-stat"><strong>${videos}</strong><span>Videos</span></div><div class="am-stat"><strong>${state.items.filter(x=>x.published!==false).length}</strong><span>Published</span></div>`}render()}catch(e){$('mediaList').innerHTML='<div class="am-empty"><strong>Unable to load the media library</strong><span>Please refresh the page and try again.</span></div>';notify(e.message||'Unable to load media.',true)}}
async function feature(id,on){const r=await api(`/api/media/${Number(id)}/featured`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({featured:Boolean(on)})});if(!r.ok)throw new Error(await readError(r,'Unable to update the Featured Video.'));return r.json()}
async function upload(e){e.preventDefault();const f=state.uploadFiles[0]||$('amFile').files?.[0];if(!f)return notify('Choose a media file first.',true);if(f.size>50*1024*1024)return notify('The selected file is larger than 50 MB.',true);const wants=$('amUploadFeatured').checked&&String(f.type||'').startsWith('video/');const b=$('amUploadButton');b.disabled=true;b.textContent='Uploading…';try{const fd=new FormData();fd.append('title',$('amUploadTitle').value.trim());fd.append('category',$('amUploadCategory').value);fd.append('description',$('amUploadDescription').value.trim());fd.append('published',$('amUploadPublished').value==='published'?'true':'false');fd.append('file',f);const r=await api('/api/media',{method:'POST',body:fd,cache:'no-store'});if(!r.ok)throw new Error(await readError(r,'Upload failed.'));const saved=await r.json();if(wants&&saved?.id)await feature(saved.id,true);notify(wants?'Media uploaded and set as the Featured Video.':'Media uploaded successfully.');state.uploadFiles=[];$('amUploadForm').reset();$('amFileStatus').textContent='No file selected.';await loadMedia()}catch(e){notify(e.message||'Upload failed.',true)}finally{b.disabled=false;b.textContent='Upload media'}}
async function copyUrl(url,b){try{await navigator.clipboard.writeText(url);b.textContent='Copied';notify('Public media URL copied.')}catch{notify('Could not copy the URL.',true)}setTimeout(()=>b.textContent='Copy URL',1200)}
window.openMediaEditor=function(item){ensureModalControl();if(!item)return;$('editMediaId').value=item.id;$('editMediaTitle').value=item.title||'';$('editMediaDescription').value=item.description||'';$('editMediaCategory').value=item.category||'general';$('mediaModalMeta').textContent=`${typeLabel(item.type)} · ${item.url||''}`;const i=$('mediaModalFeatured'),o=$('mediaFeaturedOption');if(i)i.checked=item.type==='video'&&item.featured===true;if(o){o.classList.toggle('hidden',item.type!=='video');if(i)i.disabled=item.type!=='video}$('mediaModal').classList.remove('hidden')};
window.closeMediaEditor=function(){$('mediaModal').classList.add('hidden')};
window.saveMediaEdit=async function(e){e.preventDefault();const id=Number($('editMediaId').value),item=state.items.find(x=>Number(x.id)===id),b=e.target.querySelector('button.primary');const want=Boolean(item?.type==='video'&&$('mediaModalFeatured')?.checked),was=Boolean(item?.type==='video'&&item?.featured===true);const payload={title:$('editMediaTitle').value.trim(),description:$('editMediaDescription').value.trim(),category:$('editMediaCategory').value};if(!payload.title)return notify('Title is required.',true);b.disabled=true;b.textContent='Saving…';try{const r=await api('/api/media/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});if(!r.ok)throw new Error(await readError(r,'Unable to save media changes.'));if(want!==was)await feature(id,want);closeMediaEditor();notify(want?'Media updated and set as Featured Video.':(!want&&was?'Media updated and Featured Video cleared.':'Media details updated.'));await loadMedia()}catch(e){notify(e.message||'Unable to save media changes.',true)}finally{b.disabled=false;b.textContent='Save Changes'}};
window.delMedia=async function(id){if(!confirm('Delete this media item?'))return;try{const r=await api('/api/media/'+id,{method:'DELETE',cache:'no-store'});if(!r.ok)throw new Error(await readError(r,'Delete failed.'));notify('Media deleted.');await loadMedia()}catch(e){notify(e.message||'Delete failed.',true)}};
window.loadMedia=loadMedia;window.initAdminMedia=loadMedia;
})();