(function(){
  const $=id=>document.getElementById(id);
  const api=(url,opt={})=>fetch(url,{credentials:'include',...opt});
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const notify=(t,err=false)=>{const n=$('notice');if(!n)return;n.textContent=t;n.className='notice show'+(err?' error':'');setTimeout(()=>n.className='notice',4500)};
  window.copyMediaUrl=async function(url,button){const original=button.textContent;button.disabled=true;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(url)}else{const input=document.createElement('textarea');input.value=url;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.focus();input.select();if(!document.execCommand('copy'))throw new Error('Clipboard copy blocked');input.remove()}button.textContent='Copied!';notify('Public media URL copied to clipboard.')}catch(e){button.textContent='Copy failed';notify('Could not copy the URL. Please use Open URL and copy it manually.',true)}finally{setTimeout(()=>{button.disabled=false;button.textContent=original},1800)}};
  window.openMediaEditor=function(item){$('editMediaId').value=item.id;$('editMediaTitle').value=item.title||'';$('editMediaDescription').value=item.description||'';$('editMediaCategory').value=item.category||'general';$('mediaModalMeta').textContent=`${item.type||'media'} · ${item.url||''}`;$('mediaModal').classList.remove('hidden');setTimeout(()=>$('editMediaTitle').focus(),0)};
  window.closeMediaEditor=function(){$('mediaModal').classList.add('hidden')};
  window.saveMediaEdit=async function(e){e.preventDefault();const id=Number($('editMediaId').value);const payload={title:$('editMediaTitle').value.trim(),description:$('editMediaDescription').value.trim(),category:$('editMediaCategory').value};if(!payload.title){notify('Title is required.',true);return}const button=e.target.querySelector('button.primary');button.disabled=true;button.textContent='Saving…';try{const r=await api('/api/media/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){notify((await r.json()).error||'Unable to save media changes.',true);return}closeMediaEditor();notify('Media details updated successfully.');await loadMedia()}catch(error){notify('Unable to save media changes.',true)}finally{button.disabled=false;button.textContent='Save Changes'}};
  window.delMedia=async function(id){if(!confirm('Delete this media item?'))return;const r=await api('/api/media/'+id,{method:'DELETE'});if(r.ok){notify('Media deleted.');loadMedia()}else notify((await r.json()).error||'Delete failed.',true)};
  window.loadMedia=async function(){const b=$('mediaList');if(!b)return;b.textContent='Loading…';try{const r=await api('/api/media');if(!r.ok)throw new Error('Unable to load media.');const items=await r.json();b.innerHTML=items.length?items.map(x=>`<div class="media">${x.type==='image'?`<img class="thumb" src="${esc(x.url)}" alt="${esc(x.title)}">`:'<div class="thumb"></div>'}<div class="mi"><strong>${esc(x.title)}</strong><small>${esc(x.category)} · ${esc(x.type)}${x.description?` · ${esc(x.description)}`:''}</small><small><a href="${esc(x.url)}" target="_blank" rel="noopener">Open URL</a></small></div><div class="media-actions"><button class="secondary small" onclick='copyMediaUrl(${JSON.stringify(x.url)},this)'>Copy URL</button><button class="secondary small" onclick='openMediaEditor(${JSON.stringify(x).replace(/</g,'\\u003c')})'>Edit</button><button class="danger small" onclick="delMedia(${Number(x.id)})">Delete</button></div></div>`).join(''):'<div class="empty">No media uploaded yet.</div>'}catch(e){b.innerHTML='<div class="empty">Unable to load media.</div>'}};
  window.upload=async function(e){e.preventDefault();const r=await api('/api/media',{method:'POST',body:new FormData(e.target)});if(!r.ok){notify((await r.json()).error||'Upload failed.',true);return}e.target.reset();notify('Media uploaded successfully.');loadMedia()};
  const modal=$('mediaModal');if(modal)modal.addEventListener('click',e=>{if(e.target===modal)closeMediaEditor()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('mediaModal'))closeMediaEditor()});
})();
