(function(){
  const api=()=>window.adminApi||((url,options)=>fetch(url,{credentials:'include',...(options||{})}));
  async function loadAuthenticatedData(){if(window.loadSiteContent)await window.loadSiteContent();if(window.loadAdminComments)await window.loadAdminComments();if(window.loadMedia)await window.loadMedia();}
  function showApp(){document.getElementById('login')?.classList.add('hidden');document.getElementById('app')?.classList.remove('hidden');}
  function passwordSetup(){
    document.getElementById('firstPasswordSetup')?.remove();
    const box=document.createElement('div');box.id='firstPasswordSetup';box.className='modal';box.innerHTML=`<div class="modal-card"><h2>Welcome — set your administrator password</h2><p class="muted">This is your first login. Choose a private password now. It must be at least 10 characters and contain at least one letter and one number.</p><form id="firstPasswordForm"><label>New password</label><input id="firstPassword" type="password" minlength="10" autocomplete="new-password" required><label>Confirm password</label><input id="firstPasswordConfirm" type="password" minlength="10" autocomplete="new-password" required><p id="firstPasswordMsg"></p><div class="toolbar" style="justify-content:flex-end;margin-top:14px"><button class="primary">Set Password & Continue</button></div></form></div>`;document.body.appendChild(box);
    box.querySelector('form').onsubmit=async e=>{e.preventDefault();const p=document.getElementById('firstPassword').value,c=document.getElementById('firstPasswordConfirm').value,msg=document.getElementById('firstPasswordMsg');if(p!==c){msg.textContent='Passwords do not match.';return;}msg.textContent='Saving…';try{const r=await api()('/api/admin/first-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Unable to set password.');box.remove();showApp();await loadAuthenticatedData();if(window.loadAdminModules)await window.loadAdminModules();}catch(err){msg.textContent=err.message;}};
  }
  async function processLoginResponse(data,msg){if(data.requiresPasswordSetup){if(msg)msg.textContent='';passwordSetup();return true;}if(msg)msg.textContent='';showApp();await loadAuthenticatedData();if(window.loadAdminModules)await window.loadAdminModules();return true;}
  window.adminSession={
    login:async function(event){event?.preventDefault();const username=document.getElementById('username')?.value.trim()||'',password=document.getElementById('password')?.value||'',msg=document.getElementById('loginMsg');if(msg)msg.textContent='Signing in…';try{const r=await api()('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Login failed.');return processLoginResponse(data,msg);}catch(error){if(msg)msg.textContent=error.message||'Login failed.';return false;}},
    logout:async function(){try{await api()('/api/admin/logout',{method:'POST'});}finally{location.reload();}},
    check:async function(){const status=document.getElementById('apiStatus');try{const r=await api()('/api/admin/session');const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error();if(status){status.textContent='API online';status.className='status ok';}if(data.user?.password_setup_only){showApp();passwordSetup();return true;}showApp();await loadAuthenticatedData();return true;}catch(error){if(status){status.textContent='API offline';status.className='status bad';}return false;}}
  };
  window.login=event=>window.adminSession.login(event);window.logout=()=>window.adminSession.logout();window.checkApi=()=>window.adminSession.check();window.initAdminSession=()=>window.adminSession.check();
})();
