(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const api=(url,opt={})=>window.adminApi?window.adminApi(url,opt):fetch(url,{credentials:'include',cache:'no-store',...opt});
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const categories=['general','hero','logo','gallery','services','about','events','resources','sermons','youth','worship','documents','other'];
  const state={items:[],query:'',type:'all',category:'all',sort:'newest',view:'grid',uploadFiles:[]};
  const readError=async(r,fallback)=>{try{const data=await r.json();return data?.error||fallback}catch{return fallback}};
  const notify=(t,err=false)=>window.showAdminMessage?window.showAdminMessage(t,err):undefined;
  const date=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})};
  const typeLabel=t=>({image:'Image',video:'Video',audio:'Audio',document:'PDF'}[t]||'Media');
  const typeIcon=t=>({image:'▧',video:'▶',audio:'♫',document:'PDF'}[t]||'◆');
  function ensureCss(){if(document.querySelector('link[data-admin-media-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/admin/admin-media.css?v='+(window.__ADMIN_BUILD_VERSION||Date.now());l.dataset.adminMediaCss='true';document.head.appendChild(l)}
  function normalizeMedia(data){return Array.isArray(data)?data:(Array.isArray(data?.items)?data.items:Array.isArray(data?.media)?data.media:[])}
  function filtered(){let a=state.items.filter(x=>{const q=state.query.toLowerCase();return(!q||[x.title,x.description,x.category,x.type].join(' ').toLowerCase().includes(q))&&(state.type==='all'||x.type===state.type)&&(state.category==='all'||String(x.category||'general').toLowerCase()===state.category)});a.sort((x,y)=>state.sort==='name'?(x.title||'').localeCompare(y.title||''):state.sort==='oldest'?new Date(x.created_at||0)-new Date(y.created_at||0):new Date(y.created_at||0)-new Date(x.created_at||0));return a}
  function preview(x){if(x.type==='image')return `<img src="${esc(x.url)}" alt="${esc(x.title)}" loading="lazy">`;if(x.type==='video')return `<video src="${esc(x.url)}" controls preload="metadata"></video>`;if(x.type==='audio')return `<audio src="${esc(x.url)}" controls preload="metadata"></audio>`;return `<div class="am-file-icon">${typeIcon(x.type)}</div>`}
  function card(x){return `<article class="am-card"><div class="am-preview">${preview(x)}<span class="am-type">${esc(typeLabel(x.type))}</span></div><div class="am-card-body"><div class="am-card-title" title="${esc(x.title)}">${esc(x.title)}</div><div class="am-card-meta">${esc(x.category||'general')} · ${esc(date(x.created_at))} · ${x.published===false?'Draft':'Published'}</div><div class="am-card-desc">${esc(x.description||'No description added.')}</div><div class="am-card-actions"><button class="secondary small" type="button" data-copy="${esc(x.url)}">Copy URL</button><button class="secondary small" type="button" data-edit='${esc(JSON.stringify(x))}'>Edit</button><button class="danger small" type="button" data-delete="${Number(x.id)}">Delete</button></div></div></article>`}
  function renderLibrary(){const box=$('mediaList'),items=filtered();if(!box)return;box.className=state.view==='list'?'am-list':'am-library';box.innerHTML=items.length?items.map(card).join(''):`<div class="am-empty"><strong>${state.items.length?'No matching media':'Your media library is empty'}</strong><span>${state.items.length?'Try another search or filter.':'Upload your first photo, video, audio file or PDF above.'}</span></div>`;box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyMediaUrl(b.dataset.copy,b));box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openMediaEditor(JSON.parse(b.dataset.edit)));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>delMedia(Number(b.dataset.delete)))}
  function renderStats(){const el=$('amStats');if(!el)return;const count=t=>state.items.filter(x=>x.type===t).length;el.innerHTML=`<div class="am-stat"><strong>${state.items.length}</strong><span>Library items</span></div><div class="am-stat"><strong>${count('image')}</strong><span>Images</span></div><div class="am-stat"><strong>${count('video')+count('audio')}</strong><span>Video & audio</span></div><div class="am-stat"><strong>${state.items.filter(x=>x.published!==false).length}</strong><span>Published to website</span></div>`}
  function shell(){const root=$('media');if(!root)return;root.innerHTML=`<div class="am-shell"><section class="am-hero"><div><h2>Media Center</h2><p>Upload, organize and publish the church's photos, videos, audio and documents.</p></div><div id="amStats" class="am-stats"></div></section><section class="card"><div class="am-section-head"><div><h3>Upload media</h3><p>Upload the file and enter the information that will identify it in the Media Library and on the public Media page.</p></div></div><form id="amUploadForm"><div id="amDrop" class="am-drop"><div class="am-drop-icon">↥</div><strong>Drop media here</strong><p>Images, videos, audio and PDFs are supported. Maximum file size is 50 MB.</p><button class="secondary small" type="button" id="amChoose">Choose file</button><input id="amFile" type="file" accept="image/*,video/*,audio/*,application/pdf"></div><div class="am-upload-meta"><label>Title<input id="amUploadTitle" maxlength="200" placeholder="e.g. Sunday Worship — 5 September" required></label><label>Category<select id="amUploadCategory">${categories.map(c=>`<option>${c}</option>`).join('')}</select></label></div><label>Description<textarea id="amUploadDescription" maxlength="2000" placeholder="Describe the media for visitors and future administrators."></textarea></label><div class="am-inline-grid"><label>Visibility<select id="amUploadPublished"><option value="published">Published</option><option value="draft">Draft</option></select></label></div><div class="am-upload-actions"><button class="primary" type="submit" id="amUploadButton">Upload media</button></div><div id="amFileStatus" class="am-status">No file selected.</div></form></section><section class="card"><div class="am-section-head"><div><h3>Media Library</h3><p id="amResultText">Browse every uploaded asset.</p></div><button class="secondary small" type="button" id="amRefresh">Refresh</button></div><div class="am-toolbar"><div class="am-search"><input id="amSearch" placeholder="Search media by title, category or description…" aria-label="Search media"></div><select id="amType" class="am-filter" aria-label="Filter by type"><option value="all">All types</option><option value="image">Images</option><option value="video">Videos</option><option value="audio">Audio</option><option value="document">PDFs</option></select><select id="amCategory" class="am-filter" aria-label="Filter by type"><option value="all">All categories</option>${categories.map(c=>`<option value="${c}">${c}</option>`).join('')}</select><select id="amSort" class="am-filter" aria-label="Sort media"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select><div class="am-view"><button type="button" id="amGrid" class="active">▦ Grid</button><button type="button" id="amList">☰ List</button></div></div><div id="mediaList" class="am-library"><div class="am-empty">Loading media…</div></div></section></div>`;bindShell()}
  function bindShell(){const file=$('amFile'),drop=$('amDrop');$('amChoose').onclick=()=>file.click();file.onchange=()=>setFiles(file.files);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,ev=>{ev.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,ev=>{ev.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',ev=>setFiles(ev.dataTransfer.files));$('amUploadForm').onsubmit=upload;$('amRefresh').onclick=loadMedia;$('amSearch').oninput=e=>{state.query=e.target.value;updateResults()};$('amType').onchange=e=>{state.type=e.target.value;updateResults()};$('amCategory').onchange=e=>{state.category=e.target.value;updateResults()};$('amSort').onchange=e=>{state.sort=e.target.value;updateResults()};$('amGrid').onclick=()=>setView('grid');$('amList').onclick=()=>setView('list')}
  function setFiles(files){state.uploadFiles=files?.length?[files[0]]:[];const f=state.uploadFiles[0];$('amFileStatus').textContent=f?`${f.name} · ${(f.size/1024/1024).toFixed(1)} MB`:'No file selected.';if(f&&!$('amUploadTitle').value)$('amUploadTitle').value=f.name.replace(/\.[^.]+$/,'').slice(0,200)}
  function setView(view){state.view=view;$('amGrid').classList.toggle('active',view==='grid');$('amList').classList.toggle('active',view==='list');renderLibrary()}
  function updateResults(){const n=filtered().length;$('amResultText').textContent=`Showing ${n} of ${state.items.length} media ${n===1?'item':'items'}.`;renderLibrary()}
  async function loadMedia(){ensureCss();shell();const box=$('mediaList');if(box)box.innerHTML='<div class="am-empty"><strong>Loading media…</strong><span>Fetching the Media Library.</span></div>';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);let r;try{r=await api('/api/media',{signal:controller.signal,cache:'no-store',headers:{'Cache-Control':'no-cache'}})}finally{clearTimeout(timer)}if(!r.ok)throw new Error(await readError(r,'Unable to load media.'));state.items=normalizeMedia(await r.json());renderStats();updateResults()}catch(e){if(box)box.innerHTML=`<div class="am-empty"><strong>Unable to load the media library</strong><span>${esc(e?.name==='AbortError'?'The media request timed out.':'Please refresh the page and try again.')}</span></div>`;notify(e.message||'Unable to load media.',true)}}
  async function upload(e){e.preventDefault();const f=state.uploadFiles[0]||$('amFile').files?.[0];if(!f){notify('Choose a media file first.',true);return}if(f.size>50*1024*1024){notify('The selected file is larger than 50 MB.',true);return}const button=$('amUploadButton');button.disabled=true;button.textContent='Uploading…';try{const fd=new FormData();fd.append('title',$('amUploadTitle').value.trim());fd.append('category',$('amUploadCategory').value);fd.append('description',$('amUploadDescription').value.trim());fd.append('published',$('amUploadPublished').value==='published'?'true':'false');fd.append('file',f);const r=await api('/api/media',{method:'POST',body:fd,cache:'no-store'});if(!r.ok){notify(await readError(r,'Upload failed.'),true);return}await r.json();notify('Media uploaded successfully. The Media Library and website are now refreshing.');state.uploadFiles=[];$('amUploadForm').reset();$('amFileStatus').textContent='No file selected.';await loadMedia()}catch(e){notify(e?.message||'Upload failed. Please try again.',true)}finally{button.disabled=false;button.textContent='Upload media'}}
  async function copyMediaUrl(url,button){const original=button.textContent;button.disabled=true;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(url);else{const input=document.createElement('textarea');input.value=url;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.focus();input.select();if(!document.execCommand('copy'))throw new Error();input.remove()}button.textContent='Copied';notify('Public media URL copied to clipboard.')}catch(e){button.textContent='Copy failed';notify('Could not copy the URL.',true)}finally{setTimeout(()=>{button.disabled=false;button.textContent=original},1500)}}
  window.copyMediaUrl=copyMediaUrl;
  window.openMediaEditor=function(item){$('editMediaId').value=item.id;$('editMediaTitle').value=item.title||'';$('editMediaDescription').value=item.description||'';$('editMediaCategory').value=item.category||'general';$('mediaModalMeta').textContent=`${typeLabel(item.type)} · ${item.url||''}`;$('mediaModal').classList.remove('hidden');setTimeout(()=>$('editMediaTitle').focus(),0)};
  window.closeMediaEditor=function(){$('mediaModal').classList.add('hidden')};
  window.saveMediaEdit=async function(e){e.preventDefault();const id=Number($('editMediaId').value),payload={title:$('editMediaTitle').value.trim(),description:$('editMediaDescription').value.trim(),category:$('editMediaCategory').value};if(!payload.title){notify('Title is required.',true);return}const button=e.target.querySelector('button.primary');button.disabled=true;button.textContent='Saving…';try{const r=await api('/api/media/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});if(!r.ok){notify(await readError(r,'Unable to save media changes.'),true);return}closeMediaEditor();notify('Media details updated.');await loadMedia()}catch(e){notify('Unable to save media changes.',true)}finally{button.disabled=false;button.textContent='Save Changes'}};
  window.delMedia=async function(id){if(!confirm('Delete this media item?'))return;try{const r=await api('/api/media/'+id,{method:'DELETE',cache:'no-store'});if(!r.ok){notify(await readError(r,'Delete failed.'),true);return}notify('Media deleted.');await loadMedia()}catch(e){notify('Delete failed.',true)}};
  window.loadMedia=loadMedia;
  window.initAdminMedia=loadMedia;
})();