(function(){
'use strict';
const api=()=>window.adminApi||((url,options)=>fetch(url,{credentials:'include',...(options||{})}));
function installLoginDesign(){if(typeof window.applyAdminLoginUI==='function')window.applyAdminLoginUI()}
async function loadLoginBranding(){try{const r=await fetch('/api/site/content',{credentials:'include',cache:'no-store'});if(!r.ok)return;const payload=await r.json().catch(()=>null);window.refreshAdminLoginBranding?.(payload)}catch(error){console.debug('Admin login branding unavailable:',error.message)}}
function setAuthenticatedUI(authenticated){if(typeof window.setAdminAuthenticatedUI==='function')window.setAdminAuthenticatedUI(!!authenticated);document.body.classList.toggle('admin-login-page',!authenticated)}
function showSetup(username=''){const value=String(username||'').trim();window.location.assign(value?`/admin/admin-access.html?username=${encodeURIComponent(value)}`:'/admin/admin-access.html')}
function showApp(){document.getElementById('login')?.classList.add('hidden');document.getElementById('app')?.classList.remove('hidden');setAuthenticatedUI(true)}
function showLogin(){document.getElementById('app')?.classList.add('hidden');document.getElementById('login')?.classList.remove('hidden');setAuthenticatedUI(false);installLoginDesign();loadLoginBranding()}
function showLogoutAnimation(){if(document.getElementById('adminLogoutScreen'))return Promise.resolve();const overlay=document.createElement('div');overlay.id='adminLogoutScreen';overlay.setAttribute('aria-live','polite');overlay.innerHTML='<div class="admin-logout-orb" aria-hidden="true"></div><div class="admin-logout-card"><div class="admin-logout-icon" aria-hidden="true"><span></span></div><p class="admin-logout-kicker">Administrator portal</p><h2>Signing you out</h2><p>Your administrator session is being securely closed…</p><div class="admin-logout-track"><span></span></div></div>';document.body.appendChild(overlay);document.body.classList.add('admin-logging-out');return new Promise(resolve=>setTimeout(resolve,760))}
window.adminSession={
login:async function(event){event?.preventDefault();if(window.__adminLoggingIn)return false;window.__adminLoggingIn=true;const username=document.getElementById('username')?.value.trim()||'';const password=document.getElementById('password')?.value||'';const msg=document.getElementById('loginMsg');if(!username||!password){if(msg)msg.textContent='Enter your username and password.';window.__adminLoggingIn=false;return false}if(msg)msg.textContent='Signing in…';try{const r=await api()('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await r.json().catch(()=>({}));if(!r.ok){if(data.requiresPasswordSetup){showSetup(username);return false}throw new Error(data.error||'Login failed.')}window.__adminExplicitLogin=true;window.__adminAuthenticated=true;window.__adminUser=data.user||data.admin||null;if(msg)msg.textContent='Loading administration…';if(typeof window.loadAdminModules!=='function')throw new Error('Administrator components are unavailable.');const ready=await window.loadAdminModules(true);if(!ready)throw new Error('The administration panel could not finish loading.');showApp();return true}catch(error){window.__adminAuthenticated=false;window.__adminExplicitLogin=false;setAuthenticatedUI(false);showLogin();if(msg)msg.textContent=error.message||'Login failed.';return false}finally{window.__adminLoggingIn=false}},
logout:async function(){if(window.__adminLoggingOut)return;window.__adminLoggingOut=true;setAuthenticatedUI(false);const animation=showLogoutAnimation();try{await api()('/api/admin/logout',{method:'POST'})}finally{await animation;window.__adminAuthenticated=false;window.__adminExplicitLogin=false;location.reload()}},
check:async function(){return window.__adminAuthenticated===true}
};
window.login=event=>window.adminSession.login(event);window.logout=()=>window.adminSession.logout();window.checkApi=()=>window.adminSession.check();window.initAdminSession=()=>window.adminSession.check();
// Do not rebuild the login form here. admin-loader owns the initial login transition.
})();