(function(){
  'use strict';
  const DEFAULT_NAME='Church Administration';
  const DEFAULT_ACCENT='#0b6bcb';
  let screen=null, statusNode=null, nameNode=null, logoNode=null, errorNode=null;
  let visible=false;
  const validAccent=v=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v);
  const resolveUrl=value=>{if(value==null)return '';if(typeof value==='object'){for(const k of ['url','src','publicUrl','public_url','logoUrl','logo_url','fileUrl','file_url','path','logo','image','thumbnail','value']){const r=resolveUrl(value[k]);if(r)return r}return ''}const raw=String(value).trim();if(!raw)return '';try{const u=new URL(raw,location.origin);return ['http:','https:','data:','blob:'].includes(u.protocol)?u.href:''}catch(_){return ''}};
  function loadStyles(){if(document.getElementById('adminLoadingStyles'))return;const link=document.createElement('link');link.id='adminLoadingStyles';link.rel='stylesheet';link.href='/admin/admin-loading.css?v=1';document.head.appendChild(link)}
  function build(){if(screen)return;loadStyles();screen=document.createElement('div');screen.id='adminLoadingScreen';screen.className='is-hidden';screen.setAttribute('aria-hidden','true');screen.innerHTML='<div class="admin-loader-orb" aria-hidden="true"></div><div class="admin-loader-card" role="status" aria-live="polite"><div class="admin-loader-logo"><div class="admin-loader-logo-fallback"></div></div><p class="admin-loader-kicker">Administrator portal</p><p class="admin-loader-name" data-loader-name>'+DEFAULT_NAME+'</p><p class="admin-loader-status" data-loader-status>Preparing your administration workspace…</p><div class="admin-loader-track" aria-hidden="true"><div class="admin-loader-progress"></div></div><div class="admin-loader-dots" aria-hidden="true"><span></span><span></span><span></span></div><div class="admin-loader-error" data-loader-error hidden></div></div>';document.body.appendChild(screen);statusNode=screen.querySelector('[data-loader-status]');nameNode=screen.querySelector('[data-loader-name]');logoNode=screen.querySelector('.admin-loader-logo');errorNode=screen.querySelector('[data-loader-error]');loadBranding()}
  function setTheme(theme){const t=theme||{};const accent=validAccent(t.accent)?t.accent:DEFAULT_ACCENT;document.documentElement.style.setProperty('--admin-loader-accent',accent);document.documentElement.style.setProperty('--admin-accent',accent)}
  async function loadBranding(payload){try{if(payload){applyBranding(payload);return}const r=await fetch('/api/site/content',{credentials:'include',cache:'no-store'});if(!r.ok)return;applyBranding(await r.json().catch(()=>null))}catch(_){} }
  function applyBranding(payload){const data=payload?.content||payload||{};setTheme(data.theme);const name=data.churchName||data.church_name||data.name||data.site?.churchName||data.site?.church_name;if(name&&nameNode)nameNode.textContent=String(name);const logo=resolveUrl(data.logo||data.churchLogo||data.logoUrl||data.logo_url||data.site?.logo||data.site?.logoUrl);if(logo&&logoNode){const img=document.createElement('img');img.alt='';img.src=logo;img.onload=()=>logoNode.replaceChildren(img);img.onerror=()=>{}}}
  function show(message){build();visible=true;screen.classList.remove('is-hidden');screen.setAttribute('aria-hidden','false');if(errorNode){errorNode.hidden=true;errorNode.textContent=''}if(statusNode&&message)statusNode.textContent=message;loadBranding();}
  function setMessage(message){build();if(statusNode&&message)statusNode.textContent=message;if(visible)screen.classList.remove('is-hidden')}
  function hide(){if(!screen)return;visible=false;screen.classList.add('is-hidden');screen.setAttribute('aria-hidden','true');}
  function showError(message,retry){build();visible=true;screen.classList.remove('is-hidden');screen.setAttribute('aria-hidden','false');if(statusNode)statusNode.textContent='The administration panel could not finish loading.';if(errorNode){errorNode.hidden=false;errorNode.innerHTML='';const text=document.createElement('div');text.textContent=message||'Please try again.';errorNode.appendChild(text);if(typeof retry==='function'){const button=document.createElement('button');button.type='button';button.textContent='Retry';button.addEventListener('click',retry);errorNode.appendChild(button)}}}
  window.adminLoadingScreen={show,setMessage,hide,showError,loadBranding,applyBranding,get visible(){return visible}};
})();
