(function(){
  const mount=document.getElementById('adminHeader');
  if(!mount)return;
  window.__ADMIN_BUILD_VERSION=Date.now().toString();
  if(!document.querySelector('link[data-admin-header-css]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/admin/admin-header.css?v='+encodeURIComponent(window.__ADMIN_BUILD_VERSION);link.dataset.adminHeaderCss='true';document.head.appendChild(link)}
  if(!document.querySelector('link[data-admin-header-icons-css]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/admin/admin-header-icons.css?v='+encodeURIComponent(window.__ADMIN_BUILD_VERSION);link.dataset.adminHeaderIconsCss='true';document.head.appendChild(link)}
  mount.innerHTML='<header class="admin-header"><div class="admin-header__brand"><img class="admin-header__logo" data-admin-header-logo alt="Church logo"><div class="admin-header__brand-text"><strong class="admin-header__church-name" data-admin-header-name>Kingdom Fellowship Christian Church</strong><span class="admin-header__admin-label">Admin</span></div></div><div class="admin-header__actions"><span id="apiStatus" class="admin-header__status" title="API status"><span class="admin-header__status-text">Checking…</span></span><a class="admin-header__icon-button admin-header__tooltip admin-header__back" href="/" aria-label="Back to website" title="Back to website"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 18l-6-6 6-6"></path><path d="M9 12h11"></path></svg></a><button id="adminLogout" class="admin-header__icon-button admin-header__tooltip admin-header__logout" type="button" onclick="logout()" aria-label="Log out" title="Log out" hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 17l5-5-5-5"></path><path d="M15 12H3"></path><path d="M14 4h5a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-5"></path></svg></button></div></header>';
  function isImageMedia(item){if(!item||typeof item!=='object')return false;const type=String(item.type||item.mimeType||item.mime||'').toLowerCase();const url=String(item.url||item.src||item.path||item.fileUrl||'').toLowerCase().split('?')[0].split('#')[0];return type==='image'||type.startsWith('image/')||/\.(png|jpe?g|webp|gif|svg|avif|bmp|ico|tiff?)$/.test(url)}
  function mediaIsLogo(item){if(!item||!isImageMedia(item))return false;const category=String(item.category||item.mediaCategory||item.folder||'').toLowerCase();const name=String(item.name||item.filename||item.fileName||item.title||'').toLowerCase();return category==='logo'||category.includes('logo')||name.includes('logo')}
  function firstValue(obj,keys){for(const key of keys){const value=obj?.[key];if(typeof value==='string'&&value.trim())return value.trim()}return ''}
  function setHeaderBranding(content,mediaItems){const name=document.querySelector('[data-admin-header-name]');const img=document.querySelector('[data-admin-header-logo]');if(name)name.textContent=firstValue(content,['churchName','church_name','siteName','site_name'])||'Kingdom Fellowship Christian Church';const mediaLogo=mediaItems.find(mediaIsLogo)||mediaItems.find(isImageMedia);const logoUrl=mediaLogo?.url||mediaLogo?.src||mediaLogo?.path||mediaLogo?.fileUrl||firstValue(content,['logoUrl','logo_url','logo','churchLogo','church_logo']);if(img&&logoUrl){img.onload=()=>img.classList.add('is-ready');img.onerror=()=>img.classList.remove('is-ready');img.src=String(logoUrl)}}
  window.loadAdminBranding=async function(){try{const [r,m]=await Promise.all([fetch('/api/site/content',{credentials:'same-origin',cache:'no-store'}).catch(()=>null),fetch('/api/media',{credentials:'same-origin',cache:'no-store'}).catch(()=>null)]);const content=r?.ok?await r.json().catch(()=>({})):{};const media=m?.ok?await m.json().catch(()=>[]):[];const mediaItems=Array.isArray(media)?media:(Array.isArray(media?.items)?media.items:Array.isArray(media?.media)?media.media:[]);setHeaderBranding(content,mediaItems);return content}catch(e){return {}}};
  loadAdminBranding();
  window.setAdminAuthenticatedUI=function(authenticated){const b=document.getElementById('adminLogout');if(b)b.hidden=!authenticated;document.body.classList.toggle('admin-authenticated',!!authenticated);const duplicate=document.querySelector('.login-video-panel');if(duplicate)duplicate.remove()};
  function installPasswordToggles(){document.querySelectorAll('input[type="password"]').forEach(input=>{if(input.dataset.passwordToggleReady)return;input.dataset.passwordToggleReady='true';const wrap=document.createElement('div');wrap.className='admin-password-wrap';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const b=document.createElement('button');b.type='button';b.className='admin-password-toggle';b.textContent='Show';b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Hide':'Show'};wrap.appendChild(b)})}installPasswordToggles();new MutationObserver(installPasswordToggles).observe(document.body,{childList:true,subtree:true});
  const load=()=>{const s=document.createElement('script');s.src='/admin/admin-loader.js?v='+encodeURIComponent(window.__ADMIN_BUILD_VERSION);s.dataset.adminModule='admin-loader.js';s.onload=()=>window.loadAdminModules?.().catch(console.error);s.onerror=()=>{};document.head.appendChild(s)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();