import React,{useEffect,useState}from'react';
import{ArrowLeft,ArrowRight,Clock3,Phone,Mail,Play,Radio,Headphones,House,Menu,FileText,CalendarDays,MapPin,HeartHandshake,Users,MessageCircle,Video,Mic,Music,Image,Calendar,Search,Eye,MoreVertical}from'lucide-react';
import'./detail-pages.css';import'./detail-header-contrast.css';import'./media-cinematic.css';
const defaults={about:{eyebrow:'Who We Are',title:'About the Church',summary:'Learn who we are, what we believe and the mission God has given our church.',sections:[['Our Story',''],['Our Mission',''],['Our Vision',''],['Our Values','']]},'visit-us':{eyebrow:'Plan Your Visit',title:'Visit Us',summary:'Come as you are. We would be delighted to worship, fellowship and grow with you.',sections:[['Service Times','Join us for worship, prayer, teaching and fellowship throughout the week. Check the service schedule below for the latest times.'],['Location','Find the church location, directions and branch information here. The church office can also help you plan your journey before you arrive.'],['What to Expect','Expect a warm welcome, Christ-centred worship, biblical teaching and an opportunity to connect with other members and visitors.'],['Need Help?','Have questions before your first visit? Call or email the church team and we will be glad to help with directions, services and ministries.']]},resources:{eyebrow:'Grow in Faith',title:'Resources',summary:'Find helpful materials for discipleship, Bible study, prayer and continued spiritual growth.',sections:[['Messages & Teaching',''],['Study & Discipleship',''],['Need Help Finding Something?','']]},give:{eyebrow:'Generosity',title:'Support the Ministry',summary:'Thank you for supporting the work of the church.',sections:[['Give Responsibly',''],['A Heart of Generosity',''],['Need the Details?','']]},contact:{eyebrow:'Connect With Us',title:'Contact the Church',summary:'Have a question, need directions, want to join a ministry or need more information?',sections:[['Phone',''],['Email',''],['Message','']]}};
const slugify=v=>String(v||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const pageMenu=[['Home','home'],['Live','live_service.html'],['About','detail/about'],['Events','detail/upcoming-programs'],['Visit Us','detail/visit-us'],['Media','detail/media'],['Resources','detail/resources'],['Give','detail/give'],['Contact','detail/contact']];
function getDetail(church,key){const fallback=defaults[key]||{eyebrow:'Church Information',title:key,summary:'More information from the church.',sections:[['More Information','']]};const saved=church?.detailContent||{};const custom=[key,slugify(key),fallback.title,slugify(fallback.title)].map(k=>saved[k]).find(v=>v&&typeof v==='object');const value=custom||fallback;return{...fallback,...value,sections:Array.isArray(value.sections)&&value.sections.length?value.sections:fallback.sections};}
function goPage(path){window.location.hash=path==='home'?'home':path}
function SiteNav({church,onMenu}){return <nav className="detailSiteNav" aria-label="Main navigation">{pageMenu.map(([label,path])=><a key={path} className={path==='detail/visit-us'?'active':''} href={path==='home'?'/?entered=1#home':path==='live_service.html'?'/live_service.html':`#${path}`} onClick={e=>{if(path==='home'||path==='live_service.html'){return}e.preventDefault();goPage(path)}}>{label}</a>)}<button className="detailNavMenu" type="button" onClick={onMenu} aria-label="Open menu"><Menu size={22}/></button></nav>}
function MobileMenu({open,onClose}){if(!open)return null;return <div className="detailMobileMenu" role="dialog" aria-modal="true" aria-label="Site menu"><div className="detailMobileMenuPanel"><div className="detailMobileMenuTop"><strong>Menu</strong><button type="button" onClick={onClose} aria-label="Close menu">×</button></div>{pageMenu.map(([label,path])=><a key={path} href={path==='home'?'/?entered=1#home':path==='live_service.html'?'/live_service.html':`#${path}`} onClick={()=>onClose()}>{label}</a>)}</div></div>}
function ServiceHero({service}){return <section className="serviceHero"><div className="serviceHeroSlides"><img className="serviceHeroSlide active" src={service?.image||''} alt=""/><div className="serviceHeroShade"/></div><div className="serviceHeroContent"><span>Worship Service</span><h1>{service?.title}</h1>{service?.time&&<div className="serviceHeroSchedule"><Clock3 size={17}/>{service.time}</div>}</div></section>}
function VideoFrame({url,title,image}){if(!url)return image?<img src={image} alt=""/>:null;const youtube=url.match(/(?:youtube\.com\/(?:watch\?v=|live\/|embed\/)|youtu\.be\/)([\w-]+)/);if(youtube)return <iframe src={`https://www.youtube.com/embed/${youtube[1]}`} title={title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>;return <video src={url} poster={image||undefined} controls preload="metadata"/>}
function MediaStory({item,index,onOpen}){const[visible,setVisible]=useState(false);useEffect(()=>{const node=document.querySelector(`[data-media-story="${item.id}"]`);if(!node)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){setVisible(true);observer.disconnect()}}),{threshold:.12});observer.observe(node);return()=>observer.disconnect()},[item.id]);return <article className={`mediaStory ${visible?'isVisible':''}`} data-media-story={item.id} style={{transitionDelay:`${Math.min(index,5)*70}ms`}}><button className="mediaStoryOpen" type="button" onClick={()=>onOpen(item)} aria-label={`Open ${item.title}`}><div className="mediaFrame">{item.videoUrl?<><img src={item.imageUrl||''} alt="" className="mediaThumb"/><span className="mediaPlay"><Play size={18}/></span></>:item.imageUrl?<img src={item.imageUrl} alt={item.title||'Church media'}/>:<div className="mediaNoImage"><Radio size={28}/></div>}</div><div className="mediaStoryBody"><small>{item.category||'Media'}</small><h3>{item.title}</h3><div className="mediaMeta">{item.speaker&&<span>{item.speaker}</span>}{item.date&&<span>{item.date}</span>}</div>{item.description&&<p>{item.description}</p>}<span className="mediaOpenLabel">Open story <ArrowRight size={15}/></span></div></button></article>}
function SermonView({item,onBack}){return <section className="sermonView"><button className="sermonBack" type="button" onClick={onBack}><ArrowLeft size={17}/> Back to Media</button><div className="sermonHero"><div className="sermonVideo"><VideoFrame url={item.videoUrl} title={item.title} image={item.imageUrl}/></div><div className="sermonInfo"><span>{item.category||'Sermon'}</span><h1>{item.title}</h1><div className="sermonMeta">{item.speaker&&<span>{item.speaker}</span>}{item.date&&<span><CalendarDays size={15}/>{item.date}</span>}</div>{item.description&&<p>{item.description}</p>}<div className="mediaActions">{item.audioUrl&&<a className="mediaAction" href={item.audioUrl} target="_blank" rel="noreferrer"><Headphones size={15}/> Listen</a>}{item.documentUrl&&<a className="mediaAction alt" href={item.documentUrl} target="_blank" rel="noreferrer"><FileText size={15}/> View PDF</a>}</div></div></div>{item.sermonContent&&<article className="sermonReader"><div className="sermonReaderHeading"><FileText size={22}/><div><span>Sermon Notes</span><h2>Read the Sermon</h2></div></div><div className="mediaReaderText">{item.sermonContent}</div></article>}{!item.sermonContent&&<div className="sermonNoText"><FileText size={22}/><div><strong>Full sermon text is not available.</strong><p>Use the video, audio or document options above to experience this message.</p></div></div>}</section>}
function MediaLibrary({church}){
const[items,setItems]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState('All'),[query,setQuery]=useState('');
useEffect(()=>{fetch('/api/media',{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(d=>setItems(Array.isArray(d)?d:[])).catch(()=>{})},[]);
const catalog=(Array.isArray(church?.mediaCatalog)?church.mediaCatalog:[]).filter(x=>x&&x.published!==false);
const legacy=items.map(x=>({id:`legacy-${x.id}`,title:x.title,type:x.type,category:x.category,description:x.description,url:x.url,imageUrl:x.type==='image'?x.url:'',videoUrl:x.type==='video'?x.url:'',audioUrl:x.type==='audio'?x.url:'',documentUrl:x.type==='pdf'?x.url:''}));
const all=[...catalog,...legacy.filter(x=>!catalog.some(c=>c.videoUrl===x.videoUrl&&x.videoUrl))];
const featured=all.find(x=>x.featured&&x.videoUrl)||all.find(x=>x.videoUrl)||all[0];
const heroImage=featured?.imageUrl||all.find(x=>x.imageUrl)?.imageUrl||church?.fallbackImage||'';
const normalize=x=>String(x.category||x.type||'Media').toLowerCase();
const mediaItems=all.filter(x=>x.videoUrl||x.audioUrl||x.documentUrl||x.type==='video'||x.type==='audio');
const categories=['All','Videos','Sermons','Worship','Events'];
const filtered=mediaItems.filter(x=>{const hay=`${x.title||''} ${x.category||''} ${x.description||''}`.toLowerCase();const matchesQuery=!query||hay.includes(query.toLowerCase());if(filter==='All')return matchesQuery;if(filter==='Videos')return matchesQuery&&!!x.videoUrl;if(filter==='Sermons')return matchesQuery&&(/sermon|message|teaching/.test(normalize(x))||!!x.sermonContent);return matchesQuery&&normalize(x).includes(filter.toLowerCase())});
const photos=all.filter(x=>x.imageUrl&&!x.videoUrl).slice(0,12);
if(selected)return <SermonView item={selected} onBack={()=>setSelected(null)}/>;
const categoryCards=[['Videos',Video,'Sermons, services and events'],['Sermons',Mic,'Messages from our pastors'],['Worship',Music,'Praise and worship moments'],['Events',Calendar,'Church events and activities'],['Gallery',Image,'Photos from our community']];
return <section className="mediaHub">
<section className="mediaHubHero" style={heroImage?{backgroundImage:`linear-gradient(90deg,rgba(4,14,31,.84),rgba(4,14,31,.56)),url("${heroImage}")`}:undefined}><div className="mediaHubHeroInner"><span>Watch · Listen · Experience</span><h1>MEDIA</h1><p>Watch, listen, and experience {church?.name||church?.churchName||'our church'} wherever you are.</p><i/></div></section>
<div className="mediaHubBody">
<section className="mediaTopGrid">
{featured&&<button className="mediaFeatureCard" type="button" onClick={()=>setSelected(featured)}><div className="mediaFeatureVisual">{featured.imageUrl?<img src={featured.imageUrl} alt={featured.title||''}/>:<VideoFrame url={featured.videoUrl} title={featured.title}/>}<span className="mediaBigPlay"><Play fill="currentColor" size={30}/></span></div><div className="mediaFeatureCopy"><small>FEATURED MESSAGE</small><h2>{featured.title||'Latest Message'}</h2>{featured.speaker&&<p>{featured.speaker}</p>}<div className="mediaFeatureMeta"><span><CalendarDays size={14}/>{featured.date||'Sunday Service'}</span></div>{featured.description&&<em>{featured.description}</em>}<strong><Play size={15} fill="currentColor"/> Watch Now</strong></div></button>}
<a className="mediaLiveCard" href="/live_service.html"><div><small><Radio size={14} fill="currentColor"/> LIVE NOW</small><h2>Join us for today's service</h2><span><Radio size={16}/> Watch Live</span><p>Or visit our Live Service page <ArrowRight size={14}/></p></div></a>
</section>
<section className="mediaExplore"><div className="mediaSectionHead"><h2>Explore Media</h2><p>Browse our different media categories</p></div><div className="mediaCategoryGrid">{categoryCards.map(([label,Icon,text])=><button key={label} className={`mediaCategory ${filter===label?'active':''}`} onClick={()=>label==='Gallery'?document.getElementById('media-gallery')?.scrollIntoView({behavior:'smooth'}):setFilter(label)}><Icon size={28}/><strong>{label}</strong><span>{text}</span></button>)}</div></section>
<section className="mediaLatest"><div className="mediaLatestHead"><div><h2>Latest Media</h2><p>See our newest content</p></div><div className="mediaToolbar"><div className="mediaFilters">{categories.map(c=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search media..."/></label></div></div>
{filtered.length?<div className="mediaLatestGrid">{filtered.slice(0,8).map((item,i)=><article className="mediaHubItem" key={item.id||i}><button type="button" onClick={()=>setSelected(item)}><div className="mediaHubThumb">{item.imageUrl?<img src={item.imageUrl} alt={item.title||''}/>:<VideoFrame url={item.videoUrl} title={item.title}/>}<span className="mediaSmallPlay"><Play size={17} fill="currentColor"/></span></div><div className="mediaHubItemBody"><h3>{item.title||'Church Media'}</h3>{item.speaker&&<p>{item.speaker}</p>}<small>{item.date||item.category||'Media'}</small></div><MoreVertical size={18}/></button></article>))}</div>:<div className="mediaEmpty"><Radio size={30}/><h3>Media is being prepared</h3><p>The church media team has not published any matching media yet.</p></div>}</section>
<section className="mediaGallery" id="media-gallery"><div className="mediaGalleryHead"><div><h2>Photo Gallery</h2><p>Moments from our church community</p></div>{photos.length>6&&<button onClick={()=>setQuery('')}>View All Photos <ArrowRight size={15}/></button>}</div>{photos.length?<div className="mediaPhotoGrid">{photos.slice(0,10).map((item,i)=><button key={item.id||i} type="button" onClick={()=>setSelected(item)}><img src={item.imageUrl} alt={item.title||'Church moment'}/><span>{item.title}</span></button>))}</div>:<div className="mediaGalleryEmpty">Photos from church events will appear here.</div>}</section>
<section className="mediaSubscribe"><div><h2>Be Part of Our Story</h2><p>Stay updated with our latest messages, worship and church events.</p><a href="#detail/contact" onClick={e=>{e.preventDefault();goPage('detail/contact')}}><Eye size={16}/> Subscribe Now</a></div></section>
</div>
</section>}
function VisitContent({church,item}){const services=Array.isArray(church?.services)?church.services:[];const location=item.sections.find(s=>(Array.isArray(s)?s[0]:'')==='Location');return <><section className="visitWelcome"><div><span>Plan Your Visit</span><h2>There is a place for you here.</h2><p>Whether this is your first time or you are returning, come ready to worship, connect and encounter God in community.</p><div className="visitWelcomeActions"><a href={`tel:${church?.phone||''}`}><Phone size={16}/> Talk to the church</a><a href={`mailto:${church?.email||''}`}><Mail size={16}/> Ask a question</a></div></div><div className="visitWelcomeCard"><HeartHandshake size={28}/><strong>Come as you are</strong><p>We welcome individuals and families and look forward to meeting you.</p></div></section><section className="visitServices"><div className="visitSectionHeading"><span>Join Us</span><h2>Service Times</h2><p>Choose a gathering that works for you. Times and programme details can be updated from the admin panel.</p></div>{services.length?<div className="visitServiceGrid">{services.map((s,i)=><article key={`${s.title}-${i}`}><div className="visitServiceImage">{s.image&&<img src={s.image} alt=""/>}<div/></div><div className="visitServiceBody"><span><Clock3 size={15}/>{s.time||'Check with the church'}</span><h3>{s.title}</h3><p>Join us for worship, the Word, prayer and fellowship.</p></div></article>)}</div>:<div className="visitEmpty"><Clock3 size={26}/><strong>Service times will appear here</strong><p>Check with the church office for the latest schedule.</p></div>}</section><section className="visitInfoGrid"><article><div className="visitInfoIcon"><MapPin size={20}/></div><span>Location</span><h3>Find your way to church</h3><p>{Array.isArray(location)?location[1]:'Our location and branch information will be provided here.'}</p><a href="#contact" onClick={e=>{e.preventDefault();goPage('detail/contact')}}>Get directions & contact <ArrowRight size={15}/></a></article><article><div className="visitInfoIcon"><Users size={20}/></div><span>What to Expect</span><h3>A welcoming church family</h3><p>{item.sections.find(s=>(Array.isArray(s)?s[0]:'')==='What to Expect')?.[1]||'Expect Christ-centred worship, biblical teaching, prayer and a welcoming community.'}</p></article><article><div className="visitInfoIcon"><MessageCircle size={20}/></div><span>Need Help?</span><h3>We are here for you</h3><p>{item.sections.find(s=>(Array.isArray(s)?s[0]:'')==='Need Help?')?.[1]||'Reach out before you visit and our team will gladly help you prepare.'}</p><div className="visitContactLine"><a href={`tel:${church?.phone||''}`}><Phone size={15}/>{church?.phone||'Call the church'}</a><a href={`mailto:${church?.email||''}`}><Mail size={15}/>{church?.email||'Email the church'}</a></div></article></section></>}
function DetailPage({church,type,onBack,onMenu}){const key=type||'about',item=getDetail(church,key),service=Array.isArray(church?.services)?church.services.find(s=>slugify(s?.title)===slugify(key)):null;const[mobileMenu,setMobileMenu]=useState(false);const menuHandler=onMenu||(()=>setMobileMenu(true));return <div className={`detailPage detailPage-${key}`}><header className="detailHeader"><div className="detailHeaderInner"><a className="detailBrand" href="/?entered=1#home" aria-label="Home">{church?.logo&&<img className="detailBrandLogo" src={church.logo} alt=""/>}<span><strong>{church?.name||church?.churchName||'Church'}</strong><small>{church?.tagline||''}</small></span></a><SiteNav church={church} onMenu={menuHandler}/><button className="detailMobileTrigger" type="button" onClick={menuHandler} aria-label="Open menu"><Menu size={23}/></button></div></header><main>{key==='media'?null:service?<ServiceHero service={service}/>:key==='visit-us'?<><section className="detailHero visitHero"><span>{item.eyebrow}</span><h1>{item.title}</h1><p>{item.summary}</p></section><VisitContent church={church} item={item}/></>:<section className="detailHero"><span>{item.eyebrow}</span><h1>{item.title}</h1><p>{item.summary}</p>{item.schedule&&<div className="detailSchedule"><Clock3 size={18}/>{item.schedule}</div>}</section>}{key==='media'?<MediaLibrary church={church}/>:service?<section className="detailGrid">{item.sections.map((s,i)=><article key={i}><div className="detailIcon"><ArrowRight size={18}/></div><h2>{Array.isArray(s)?s[0]:s.heading}</h2><p>{Array.isArray(s)?s[1]:s.text||s.description||''}</p></article>)}</section>:key==='visit-us'?null:<section className="detailGrid">{item.sections.map((s,i)=><article key={i}><div className="detailIcon"><ArrowRight size={18}/></div><h2>{Array.isArray(s)?s[0]:s.heading}</h2><p>{Array.isArray(s)?s[1]:s.text||s.description||''}</p></article>)}</section>}<section className="detailCta"><div><span>{church?.name||church?.churchName||'Church'}</span><h2>Have questions or want to get connected?</h2><p>Our church team will be happy to help.</p></div><div className="detailActions"><a href={`tel:${church?.phone||''}`}><Phone size={17}/> Call</a><a href={`mailto:${church?.email||''}`}><Mail size={17}/> Email</a><button onClick={onBack}><ArrowLeft size={17}/> Return to site</button></div></section></main><footer className="detailFooter"><strong>{church?.name||church?.churchName||'Church'}</strong><span>{church?.footerTagline||church?.tagline||''}</span></footer><MobileMenu open={mobileMenu} onClose={()=>setMobileMenu(false)}/></div>}
export function DetailRouter({church,type,onBack,onMenu}){return <DetailPage church={church} type={type} onBack={onBack} onMenu={onMenu}/>}
export function detailSlug(value){return slugify(value)}