import React,{useEffect,useRef,useState}from"react";
import{ArrowRight,Globe,Menu,MessageCircle,Search,Volume2,VolumeX,X,Upload,Image,Video as VideoIcon,FileText,LogOut,Save,ShieldCheck}from"lucide-react";
import{DEFAULT_SITE_CONTENT}from"../site-config.js";
import"./styles.css";

const DEFAULT_CHURCH={...DEFAULT_SITE_CONTENT,name:DEFAULT_SITE_CONTENT.churchName,slides:DEFAULT_SITE_CONTENT.gallery};

const navTargets={Home:"home",About:"about",Events:"events",Visit Us:"visit",Media:"media",Resources:"resources",Give:"give",Contact:"contact"};

function Video({videoUrl,fallbackImage}){const bgRef=useRef(null);const[failed,setFailed]=useState(false);useEffect(()=>{try{if(bgRef.current?.tagName==="IFRAME")bgRef.current.contentWindow.postMessage(JSON.stringify({event:"command",func:"mute",args:[]}),"*")}catch{}},[]);const entryUrl=videoUrl||DEFAULT_CHURCH.videoUrl;const isYouTube=/youtu\.be|youtube\.com/.test(entryUrl);let youtubeId=null;if(isYouTube){const m=entryUrl.match(/(?:v=|vi=|\/)([A-Za-z0-9_-]{11})/);if(m)youtubeId=m[1];const short=entryUrl.match(/youtu\.be\/([A-Za-z0-9_-]{11})/);if(!youtubeId&&short)youtubeId=short[1]}return <div className="media"><img className="fallback" src={fallbackImage||DEFAULT_CHURCH.fallbackImage} alt="Church congregation worshipping"/>{!failed&&isYouTube&&youtubeId?<iframe ref={bgRef} className="video" title="background-video" src={`https://www.youtube.com/embed/${youtubeId}?autoplay=1&mute=1&enablejsapi=1&controls=0&loop=1&playlist=${youtubeId}&modestbranding=1&rel=0&playsinline=1`} frameBorder="0" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen onError={()=>setFailed(true)}/>:!failed&&<video ref={bgRef} className="video" autoPlay loop muted playsInline preload="auto" poster={fallbackImage||DEFAULT_CHURCH.fallbackImage} onError={()=>setFailed(true)}><source src={entryUrl} type="video/mp4"/></video>}<div className="overlay"/></div>}

function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
function Header({menu,search,church}){const navItems=Object.keys(navTargets);return <header><button className="brand" onClick={()=>scrollToSection("home")}><span className="mark">✦</span><span><b>{church.name}</b><small>{church.tagline}</small></span></button><nav className="navLinks" aria-label="Main navigation">{navItems.map(x=><a key={x} href={`#${navTargets[x]}`} onClick={e=>{e.preventDefault();scrollToSection(navTargets[x])}}>{x}</a>)}</nav><div style={{display:"flex",alignItems:"center",gap:8}}><button className="icon menuIcon" onClick={menu} aria-label="Open menu"><Menu size={25}/></button><button className="icon" onClick={search} aria-label="Search"><Search size={21}/></button></div></header>}

function HeroCarousel({slides}){const[index,setIndex]=useState(0);useEffect(()=>{if(slides.length<2)return;const t=setInterval(()=>setIndex(i=>(i+1)%slides.length),4000);return()=>clearInterval(t)},[slides.length]);return <section className="hero carousel" id="home"><div className="carousel-inner">{slides.map((s,idx)=><div className={`carousel-slide ${idx===index?"active":""}`} key={idx}>{s.type==="video"?<video className="carousel-media" src={s.src} autoPlay loop muted playsInline/>:<img className="carousel-media" src={s.src} alt={`slide-${idx+1}`}/>}</div>)}</div></section>}

function ImageTile({item,className=""}){return <a className={`imageTile ${className}`} href={item.url||"#"} onClick={e=>{if(!item.url||item.url==="#")e.preventDefault()}} style={{"--tile-image":`url("${item.image}")`}}><span className="tileContent"><strong>{item.title}</strong>{item.text&&<small>{item.text}</small>}{item.time&&<em>{item.time}</em>}</span></a>}

function HomeContent({church}){const services=Array.isArray(church.services)?church.services:DEFAULT_CHURCH.services;const links=Array.isArray(church.links)?church.links:DEFAULT_CHURCH.links;const classes=Array.isArray(church.membershipClasses)?church.membershipClasses:DEFAULT_CHURCH.membershipClasses;return <div className="homeContent"><section className="homeSection aboutSection" id="about"><div className="sectionIntro"><span>{church.aboutEyebrow}</span><h2>{church.aboutTitle}</h2><i/></div><p>{church.aboutText}</p></section><section className="homeSection servicesSection" id="events"><div className="sectionIntro centered"><span>{church.servicesEyebrow}</span><h2>{church.servicesTitle}</h2></div><div className="tileGrid servicesGrid">{services.map((item,index)=><ImageTile key={`${item.title}-${index}`} item={item} className="serviceTile"/>)}</div></section><section className="homeSection linksSection" id="media"><div className="tileGrid linksGrid">{links.map((item,index)=><ImageTile key={`${item.title}-${index}`} item={item} className="linkTile"/>)}</div></section><section className="homeSection familySection" id="resources"><div className="sectionIntro centered"><span>{church.membershipEyebrow}</span><h2>{church.membershipTitle}</h2></div><div className="tileGrid classGrid">{classes.map((item,index)=><div className="classTile" key={`${item.title}-${index}`} style={{"--tile-image":`url("${item.image}")`}}><strong>{item.title}</strong><a href={item.registrationUrl||"#"} onClick={e=>{if(!item.registrationUrl||item.registrationUrl==="#")e.preventDefault()}}>Register Now <ArrowRight size={16}/></a></div>)}</div></section><section className="homeSection utilitySection" id="visit"><div className="sectionIntro centered"><span>Visit Us</span><h2>We'd love to worship with you</h2></div><p>{church.phone} · {church.email}</p></section><section className="homeSection utilitySection" id="give"><div className="sectionIntro centered"><span>Give</span><h2>Support the ministry</h2></div><p>Thank you for supporting the work of the church. Use the giving details provided by the church office.</p></section><section className="homeSection utilitySection" id="contact"><div className="sectionIntro centered"><span>Contact</span><h2>Get in touch</h2></div><p><a href={`tel:${church.phone}`}>{church.phone}</a> · <a href={`mailto:${church.email}`}>{church.email}</a></p></section><footer className="siteFooter"><div><strong>{church.name}</strong><span>{church.footerTagline}</span></div><div><a href={`tel:${church.phone}`}>{church.phone}</a><a href={`mailto:${church.email}`}>{church.email}</a></div><small>&copy; {new Date().getFullYear()} {church.name}. All rights reserved.</small></footer></div>}

function Drawer({open,close}){if(!open)return null;return <div className="drawer"><div className="drawerTop"><b></b><button className="close" onClick={close}><X/></button></div><nav>{Object.keys(navTargets).map(x=><a key={x} href={`#${navTargets[x]}`} onClick={e=>{e.preventDefault();close();scrollToSection(navTargets[x])}}>{x}</a>)}</nav></div>}

function SearchBox({open,close,church}){const[q,setQ]=useState("");const[results,setResults]=useState([]);useEffect(()=>{if(!q.trim()){setResults([]);return}const needle=q.toLowerCase();const data=[{title:church.aboutTitle,text:church.aboutText,id:"about"},...(church.services||[]).map(x=>({...x,id:"events"})),...(church.links||[]).map(x=>({...x,id:"media"})),...(church.membershipClasses||[]).map(x=>({...x,id:"resources"}))];setResults(data.filter(x=>`${x.title||""} ${x.text||""} ${x.description||""}`.toLowerCase().includes(needle)).slice(0,8))},[q,church]);if(!open)return null;return <div className="searchOverlay" onMouseDown={close}><div className="searchBox" onMouseDown={e=>e.stopPropagation()}><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search sermons, events, ministries..."/><button type="button" onClick={close}><X/></button>{results.length>0&&<div className="searchResults">{results.map((r,i)=><button key={`${r.title}-${i}`} onClick={()=>{close();scrollToSection(r.id)}}><strong>{r.title}</strong><small>{r.text||r.description||""}</small></button>)}</div>}{q.trim()&&!results.length&&<p className="searchEmpty">No matching content found.</p>}</div></div>}

function LandingPage(){const[menu,setMenu]=useState(false);const[search,setSearch]=useState(false);const[audioMuted,setAudioMuted]=useState(true);const[lang,setLang]=useState("EN");const[entered,setEntered]=useState(false);const[siteContent,setSiteContent]=useState(DEFAULT_CHURCH);const audioRef=useRef(null);const audioReadyRef=useRef(false);useEffect(()=>{let ignore=false;fetch('/api/site/content').then(res=>res.ok?res.json():null).then(data=>{if(!ignore&&data)setSiteContent({...DEFAULT_CHURCH,...data,name:data.churchName||data.name||DEFAULT_CHURCH.name,slides:Array.isArray(data.gallery)&&data.gallery.length?data.gallery:DEFAULT_CHURCH.slides})}).catch(()=>{});return()=>{ignore=true}},[]);const hasAudio=siteContent.audioUrl&&/youtu\.be|youtube\.com/.test(siteContent.audioUrl);let audioId=null;if(hasAudio){const m=siteContent.audioUrl.match(/(?:v=|vi=|\/)([A-Za-z0-9_-]{11})/);if(m)audioId=m[1];const short=siteContent.audioUrl.match(/youtu\.be\/([A-Za-z0-9_-]{11})/);if(!audioId&&short)audioId=short[1]}const handleToggleSound=()=>setAudioMuted(v=>!v);const slides=Array.isArray(siteContent.slides)&&siteContent.slides.length?siteContent.slides:DEFAULT_CHURCH.slides;return <main className={`page ${entered?"entered":""}`}><Video videoUrl={siteContent.videoUrl} fallbackImage={siteContent.fallbackImage}/>{entered&&<Header menu={()=>setMenu(true)} search={()=>setSearch(true)} church={siteContent}/>} {entered?<><HeroCarousel slides={slides}/><HomeContent church={siteContent}/></>:<section className="hero" id="home"><span>{siteContent.tagline}</span><h1>{siteContent.title}</h1><p>{siteContent.subtitle}</p><a className="enter" href="#home" onClick={e=>{e.preventDefault();setEntered(true);setAudioMuted(true)}}>{siteContent.cta}<ArrowRight size={17}/></a></section>}<div className="language"><Globe size={15}/><button className={lang==="EN"?"active":""} onClick={()=>setLang("EN")}>EN</button><button className={lang==="SW"?"active":""} onClick={()=>setLang("SW")}>SW</button></div>{!entered&&<button className="sound desktop" onClick={handleToggleSound}><span>SOUND</span><i/>{audioMuted?<VolumeX/>:<Volume2/>}</button>}{!entered&&<button className="sound mobile" onClick={handleToggleSound}>{audioMuted?<VolumeX/>:<Volume2/>}</button>}<button className="chat" onClick={()=>scrollToSection("contact")} aria-label="Contact church"><MessageCircle/></button><Drawer open={menu} close={()=>setMenu(false)}/><SearchBox open={search} close={()=>setSearch(false)} church={siteContent}/>{hasAudio&&audioId&&<iframe ref={audioRef} className="audio-frame" title="background-audio" src={`https://www.youtube.com/embed/${audioId}?autoplay=1&mute=1&enablejsapi=1&controls=0&loop=1&playlist=${audioId}&modestbranding=1&rel=0&origin=${window.location.origin}`} frameBorder="0" allow="autoplay; encrypted-media" onLoad={()=>{audioReadyRef.current=true}}/>}</main>}

function AdminPanel(){const[loggedIn,setLoggedIn]=useState(false);const[loginState,setLoginState]=useState({username:"",password:""});const[loading,setLoading]=useState(true);const[siteData,setSiteData]=useState(DEFAULT_SITE_CONTENT);const[mediaItems,setMediaItems]=useState([]);const[activeTab,setActiveTab]=useState("site");const[notice,setNotice]=useState("");const[uploadForm,setUploadForm]=useState({title:"",category:"general",description:"",file:null});const readSession=async()=>{try{const resp=await fetch("/api/admin/session",{credentials:"include"});if(resp.ok){setLoggedIn(true);await Promise.all([loadSiteData(),loadMedia()])}}catch{}finally{setLoading(false)}};const loadSiteData=async()=>{const r=await fetch("/api/site/content");if(r.ok)setSiteData(await r.json())};const loadMedia=async()=>{const r=await fetch("/api/media");if(r.ok)setMediaItems(await r.json())};useEffect(()=>{readSession()},[]);const login=async e=>{e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(loginState)});if(r.ok){setLoggedIn(true);setNotice("Logged in.");await Promise.all([loadSiteData(),loadMedia()])}else setNotice("Invalid username or password.")};const logout=async()=>{await fetch("/api/admin/logout",{method:"POST",credentials:"include"});setLoggedIn(false)};if(loading)return <div className="adminPage"><p>Loading…</p></div>;if(!loggedIn)return <div className="adminPage"><form onSubmit={login}><h1><ShieldCheck/> Admin Login</h1><input placeholder="Username" value={loginState.username} onChange={e=>setLoginState({...loginState,username:e.target.value})}/><input type="password" placeholder="Password" value={loginState.password} onChange={e=>setLoginState({...loginState,password:e.target.value})}/><button type="submit">Sign in</button><p>{notice}</p></form></div>;return <div className="adminPage"><header><h1>Admin</h1><button onClick={logout}><LogOut/> Log out</button></header><div className="adminTabs"><button onClick={()=>setActiveTab("site")}>Site</button><button onClick={()=>setActiveTab("media")}>Media</button></div>{notice&&<p>{notice}</p>}{activeTab==="media"?<div><h2>Media Library</h2>{mediaItems.map(item=><div key={item.id}><strong>{item.title}</strong> <small>{item.type}</small></div>)}</div>:<div><h2>Site content</h2><p>Use the existing site editor fields to update church content.</p></div>}</div>}

function App(){return window.location.pathname.startsWith("/admin")?<AdminPanel/>:<LandingPage/>}

createRoot(document.getElementById("root")).render(<App/>);
